### ISSUE TITLE
同步原来的 downloads 数据

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#108]
主要是避免单个包的历史下载数据丢失问题，全站数据我们已经有统计过。

## 核心逻辑

设定某一天是重合期，~~这一天的下载量相加~~，这一天的下载量是覆盖。这一天之后的数据忽略。

选择一个周日（反正从0点开始丢弃的数据也能被接受）开始跑，那么这一天的数据允许丢弃老 registry 的数据，因为可能会重跑多次，这样避免数据做相加导致额外增多了，宁可丢掉重合那天的数据，也不要制造多出来的下载量。

## Todos

- [X] r.cnpmjs.org datas 选择 2021-12-28
- [x] registry.npmmirror.com datas 选择 2022-01-29

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/downloads/range/2011-01-01:2024-10-02/react

https://registry.npmmirror.com/downloads/range/2011-01-01:2024-10-02/antd

**Comment by fengmk2** [comment]
在新的 npmmirror registry 切流之后跑这个同步程序，这样可以将历史的下载数据相加在一起。

**Comment by fengmk2** [comment]
以 r.cnpmjs.org 做测试

2021-12-29 09:46:05: (198.11.178.15) 修改 A 记录 默认 线路 r 值 47.241.4.205 为 CNAME 记录 默认 线路 r 值 r.cnpmjs.org.w.kunlunsl.com. (95021729) ，该记录开启了D监控，信息已同步 Uin:81715239 Real Client IP:198.11.178.15 API FROM:CONSOLE

**Comment by yuanzhian** [comment]
大佬，如果某个包的版本在新版本的源找不到，会去之前的源拉取嘛，有这个机制吗 😄

**Comment by fengmk2** [comment]
> 大佬，如果某个包的版本在新版本的源找不到，会去之前的源拉取嘛，有这个机制吗 😄

https://github.com/cnpm/cnpmcore/blob/a4429d11f4a035b63888643e940f166a1d8614e8/app/port/middleware/ErrorHandler.ts#L10 你可以看看这个 error middleware，我们在开启同步之后，如果这边包没有同步过，会 302 到上游 registry，然后后台发起一次同步任务。

**Comment by fengmk2** [comment]
@yuanzhian 这就是这个 issue 需要做的事情，还没实现。

**Comment by fengmk2** [comment]
https://r.cnpmjs.org/downloads/range/2021-01-01:2021-12-31/antd

**Comment by fengmk2** [comment]
验证成功 https://registry.nlark.com/downloads/range/2022-01-01:2022-12-31/antd

**Comment by fengmk2** [comment]
完成。
