### ISSUE TITLE
DEVELOPER. MD has a word wrong

### ISSUE THREAD

**Issue by yuanzhian** [cnpm/cnpmcore#111]
![image](https://user-images.githubusercontent.com/26033663/149690303-3485b725-6510-4d22-bba0-fdc693037842.png)

**Comment by yuanzhian** [comment]
“我们约定所有用户权限验证都在 Controller 层完全，Service 和 Repository 不做权限校验。” ，这句话的“完全”应该为“完成”。😄

**Comment by fengmk2** [comment]
@yuanzhian 来来来，正好可以贡献起来。

**Comment by yuanzhian** [comment]
最近在看源码，大佬，在哪可以看已实现的功能列表和未来规划的需求列表？😄

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/pull/112

**Comment by fengmk2** [comment]
> 最近在看源码，大佬，在哪可以看已实现的功能列表和未来规划的需求列表？😄

可以关注 https://github.com/cnpm/cnpmcore/milestone/1
目前最需要的是基于 registry api 做一个 web console。

**Comment by yuanzhian** [comment]
> > 最近在看源码，大佬，在哪可以看已实现的功能列表和未来规划的需求列表？😄
> 
> 可以关注 https://github.com/cnpm/cnpmcore/milestone/1 目前最需要的是基于 registry api 做一个 web console。

服务端渲染吗？我有看到你说用海兔，能了解下一些细节嘛，这样我可更快参与到开发 。
