### ISSUE TITLE
vega-typings 0.22.1 not found (published one month ago)

### ISSUE THREAD

**Issue by aircloud** [cnpm/cnpmcore#13]
npm: https://www.npmjs.com/package/vega-typings/v/0.22.1

not found in https://npmmirror.com/package/vega-typings

need help Thanks!

**Comment by fengmk2** [comment]
https://npmmirror.com/sync/vega-typings?spm=a2c6h.24755359.0.0.262740bbwXsS46#logid=73191557 synced now.

We support `sync button` on the page.
![image](https://user-images.githubusercontent.com/156269/144732393-ab1e9477-bc24-4b33-aa3b-ed903e2848fa.png)
