### ISSUE TITLE
npm restart 在 stop 的时候支持先关闭流量

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#132]
增加一个 /-/status 接口，让 slb 发现并自动切流。

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/151683157-44e706ca-b6be-4d4e-86ba-3d34d9d7a9a3.png)

**Comment by hyj1991** [comment]
这个问题可能和 `ulimit -c` 的配置权限也有关系，看进程刚才是正常启动的，不过这种内核参数修改确实是最好手动在机器上执行一次，放在发布脚本里估计有未知问题

**Comment by fengmk2** [comment]
慢 sql

```sql
SELECT * FROM `package_version_downloads` WHERE `package_id` = 'total' AND `year_month` >= 202101 AND `year_month` <= 202201
```

![image](https://user-images.githubusercontent.com/156269/151685234-6342f89a-ea0b-438c-aef1-d6e8dc24c3ae.png)
