### ISSUE TITLE
增加 install-node 机制，确保构建的 node 版本和实际运行的一致

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#174]
这样也可以确保我们及时升级到合适的 node 版本而不需要长期维护多个 node 版本的支持。

**Comment by fengmk2** [comment]
@popomore 找到 nodeinstall 的外部场景了 https://github.com/cnpm/nodeinstall

**Comment by popomore** [comment]
这里说的是 cnpmcore，还是 cnpm？

**Comment by fengmk2** [comment]
npx node 方式
