### ISSUE TITLE
Introduction to Hooks

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#183]
https://github.com/npm/registry/tree/master/docs/hooks

**Comment by Zian502** [comment]
参考 cnpmjs 的实现嘛
![image](https://user-images.githubusercontent.com/26033663/162922797-4acdbf78-27ab-43ba-b21d-ad2cc8a0c6f0.png)

**Comment by Zian502** [comment]
<!DOCTYPE html><figure class="md-table-fig" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">

请求路径 | 请求方法
-- | --
/-/npm/v1/hooks/hook/${id} | GET
/-/npm/v1/hooks?package=${name} | GET
/-/npm/v1/hooks/hook/${id} | DELETE
/-/npm/v1/hooks/hook/${id} | PUT
/-/npm/v1/hooks/hook | POST

</figure>

**Comment by Zian502** [comment]
<!DOCTYPE html><h2 cid="n87" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.75em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.225; cursor: text; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: rgb(238, 238, 238); white-space: pre-wrap; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">接口定义（参考 npm registry api）</span></h2><figure class="md-table-fig" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">

请求路径 | 请求方法 | 描述
-- | -- | --
/-/npm/v1/hooks/hook/${id} | GET | Fetch the hook object for the single named hook
/-/npm/v1/hooks?package=${name} | GET | npm hook ls
/-/npm/v1/hooks/hook/${id} | DELETE | npm hook rm
/-/npm/v1/hooks/hook/${id} | PUT | npm hook update
/-/npm/v1/hooks/hook | POST | npm hook add

</figure><p cid="n84" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"></p><p cid="n85" mdtype="paragraph" class="md-end-block md-p" mdlike="h2" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span class="md-block-like" style="box-sizing: border-box;"><span class="md-blockmeta" style="box-sizing: border-box; color: rgb(204, 204, 204); font-weight: 700; font-style: italic;">## </span><span class="md-header-span" style="box-sizing: border-box; font-weight: 700;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">类型定义</span></span></span></p><pre spellcheck="false" class="md-fences md-end-block ty-contain-cm modeLoaded" lang="typescript" cid="n9" mdtype="fences" style="box-sizing: border-box; overflow: visible; font-family: var(--monospace); font-size: 0.9em; display: block; break-inside: avoid; text-align: left; white-space: normal; background-image: inherit; background-size: inherit; background-attachment: inherit; background-origin: inherit; background-clip: inherit; background-color: rgb(248, 248, 248); position: relative !important; border: 1px solid rgb(231, 234, 237); border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; padding: 8px 4px 6px; margin-bottom: 15px; margin-top: 15px; width: inherit; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; background-position: inherit inherit; background-repeat: inherit inherit;"><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">type</span> <span class="cm-type" style="box-sizing: border-box;">addJson</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> {</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">type</span>: <span class="cm-type" style="box-sizing: border-box;">type</span>.<span class="cm-type" style="box-sizing: border-box;">package</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">|</span> <span class="cm-type" style="box-sizing: border-box;">type</span>.<span class="cm-type" style="box-sizing: border-box;">scope</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">|</span> <span class="cm-type" style="box-sizing: border-box;">type</span>.<span class="cm-type" style="box-sizing: border-box;">owner</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">name</span>: <span class="cm-type" style="box-sizing: border-box;">string</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">endpoint</span>: <span class="cm-type" style="box-sizing: border-box;">string</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">secret</span>: <span class="cm-type" style="box-sizing: border-box;">string</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">}</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">type</span> <span class="cm-type" style="box-sizing: border-box;">updateJson</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> {</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">endpoint</span>: <span class="cm-type" style="box-sizing: border-box;">string</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-property" style="box-sizing: border-box; color: rgb(0, 0, 0);">secret</span>: <span class="cm-type" style="box-sizing: border-box;">string</span>;</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">}</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span class="cm-keyword" style="box-sizing: border-box; color: rgb(119, 0, 136);">enum</span> <span class="cm-def" style="box-sizing: border-box; color: rgb(0, 0, 255);">type</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> {</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-def" style="box-sizing: border-box; color: rgb(0, 0, 255);">package</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-string" style="box-sizing: border-box; color: rgb(170, 17, 17);">'package'</span>,</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-def" style="box-sizing: border-box; color: rgb(0, 0, 255);">scope</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-string" style="box-sizing: border-box; color: rgb(170, 17, 17);">'scope'</span>,</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"> &nbsp;<span class="cm-def" style="box-sizing: border-box; color: rgb(0, 0, 255);">owner</span> <span class="cm-operator" style="box-sizing: border-box; color: rgb(152, 26, 26);">=</span> <span class="cm-string" style="box-sizing: border-box; color: rgb(170, 17, 17);">'owner'</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;">}</span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span><br><span role="presentation" style="box-sizing: border-box; padding-right: 0.1px;"><span cm-text="" style="box-sizing: border-box;">​</span></span></pre>

**Comment by Zian502** [comment]
> @Zian502 不走野路子了，直接走 npm registry 的 hooks 方案。

直接调用 npm registry hooks api 还是我们自己实现一套 webhook，如果自己实现的话，我在考虑能否用 egg plugin 的方案

**Comment by fengmk2** [comment]
@Zian502 直接做进 cnpmcore 里面去。
我们是私有 registry，还可以实现 global 级别的全量数据 hooks。

**Comment by Zian502** [comment]
> @Zian502 直接做进 cnpmcore 里面去。 我们是私有 registry，还可以实现 global 级别的全量数据 hooks。

了解，那要实现一套 node webhook 机制了

**Comment by fengmk2** [comment]
在 https://github.com/cnpm/cnpmcore/issues/282 实现了
