### ISSUE TITLE
bug-versions

### ISSUE THREAD

**Issue by atian25** [cnpm/cnpmcore#184]
非 cnpm cli 的客户端也能享受到 bug-versions。

之前的 https://github.com/cnpm/cnpmjs.org/pull/1683/files 似乎没迁移过来。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/pull/1684 应该是这个，我加上。

**Comment by fengmk2** [comment]
@atian25 不过这个会有问题，会导致 lock file 安装失败。还没想好怎么做才是最合适的，先 hold 了。

**Comment by atian25** [comment]
如果是有问题的版本，lock 失败也合理吧？

**Comment by fengmk2** [comment]
如果他们都认可 bug-versions 是合理的，但是目前没有这个共识。npm、yarn、pnpm cli 的负责人估计都不知道。

**Comment by fengmk2** [comment]
close by https://github.com/cnpm/cnpmcore/pull/193

**Comment by atian25** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/227713/165463509-9ec370fc-bd48-4dd5-8aae-bb865d6cc142.png">

https://github.com/cnpm/bug-versions/blob/master/package.json#L903

@fengmk2 @killagu  非 cnpm cli 的场景，我们要不要类似这个，把响应的 package.json 的 scripts 重写掉？

**Comment by fengmk2** [comment]
@atian25 来个 pr。
