### ISSUE TITLE
从 cnpm到cnpmcore怎样迁移数据库

### ISSUE THREAD

**Issue by ZhaoYuLing** [cnpm/cnpmcore#207]
公司部署的cnpm更换未cnpmcore部署之后，数据库迁移有没有可以参考的文档呀

**Comment by fengmk2** [comment]
@ZhaoYuLing 无法迁移，目前我们的做法是新建一个 cnpmcore，然后 cnpmcore 去同步老的 cnpmjs.org。
同步完成之后删除老的 cnpmjs.org，然后将 cnpmcore 的同步切换到 registry.npmmirror.com

**Comment by baxtergu** [comment]
> @ZhaoYuLing 无法迁移，目前我们的做法是新建一个 cnpmcore，然后 cnpmcore 去同步老的 cnpmjs.org。 同步完成之后删除老的 cnpmjs.org，然后将 cnpmcore 的同步切换到 registry.npmmirror.com

请问 private scope 下的包用这种同步的方式能迁移么，具体应该如何操作

**Comment by laoboxie** [comment]
> @ZhaoYuLing 无法迁移，目前我们的做法是新建一个 cnpmcore，然后 cnpmcore 去同步老的 cnpmjs.org。 同步完成之后删除老的 cnpmjs.org，然后将 cnpmcore 的同步切换到 registry.npmmirror.com

请问账号等信息也是会自动同步的吗？
