### ISSUE TITLE
Prisma: Not Found https://cdn.npmmirror.com/binaries/prisma/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/rhel-openssl-1.0.x/introspection-engine.gz

### ISSUE THREAD

**Issue by fjc0k** [cnpm/cnpmcore#209]
3.12.0 未同步

https://github.com/prisma/prisma/releases/tag/3.12.0
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/13151189/163791845-02c260d6-2598-40e0-b239-f1394d2f802e.png">

https://registry.npmmirror.com/binary.html?path=prisma/
<img width="650" alt="image" src="https://user-images.githubusercontent.com/13151189/163791903-9e62b717-4ff7-4019-a317-4b240b1c1683.png">

**Comment by fengmk2** [comment]
https://prisma-builds.s3-eu-west-1.amazonaws.com/?delimiter=/&prefix= prisma 的文件源站点也没有 3.12 的目录。

**Comment by fjc0k** [comment]
这里 all_commits 里有：

https://prisma-builds.s3-eu-west-1.amazonaws.com/?delimiter=/&prefix=all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/

**Comment by fjc0k** [comment]
@fengmk2 这个链接还是不能访问  https://cdn.npmmirror.com/binaries/prisma/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/rhel-openssl-1.0.x/introspection-engine.gz

**Comment by fengmk2** [comment]
> @fengmk2 这个链接还是不能访问 https://cdn.npmmirror.com/binaries/prisma/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/rhel-openssl-1.0.x/introspection-engine.gz

数据量比较大，还在同步，新加坡站点已经成功 https://r.cnpmjs.org/binary.html?path=prisma/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/

**Comment by fjc0k** [comment]
@fengmk2 辛苦！我现在在七牛云搞了个空间弄镜像回源了。不知道我们这个是否可以弄成镜像回源那种只在初次访问时才去拉取，这样可以避免这种文件太多的情况。

**Comment by fengmk2** [comment]
@fjc0k https://cdn.npmmirror.com/binaries/prisma/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/rhel-openssl-1.0.x/introspection-engine.gz 同步完了。

**Comment by fjc0k** [comment]
@fengmk2 👍

**Comment by fengmk2** [comment]
> @fengmk2 辛苦！我现在在七牛云搞了个空间弄镜像回源了。不知道我们这个是否可以弄成镜像回源那种只在初次访问时才去拉取，这样可以避免这种文件太多的情况。

全量同步确实无法搞定，会改成按 npm 发布的版本号来同步 https://github.com/cnpm/cnpmcore/issues/473#issuecomment-1562115738
