### ISSUE TITLE
node 17 下 cnpmcore 服务无法启动，egg 提示 scandir 对应的目录不存在

### ISSUE THREAD

**Issue by laibao101** [cnpm/cnpmcore#210]
系统版本: mac os 10.14.5
node版本：17.9.0
执行命令:  `DEBUG_LOCAL_SQL=true npm run dev`
影响范围：对生产环境暂无影响。

报错截图：
<img width="899" alt="image" src="https://user-images.githubusercontent.com/17879221/163830276-81347372-8c53-46d8-9130-d49cefceda1f.png">

**Comment by fengmk2** [comment]
cnpmcore 目前只支持跑在 node 16 下 https://github.com/cnpm/cnpmcore/blob/main/.github/workflows/nodejs.yml#L35
