### ISSUE TITLE
[BUG] 公共包 404

### ISSUE THREAD

**Issue by ObservedObserver** [cnpm/cnpmcore#218]
@kanaries/web-data-loader 这个公共包之前一直是好的，今天突然挂了。在cnpm网站上查询是404，但实际上这是一个public的包，可以在https://www.npmjs.com/package/@kanaries/web-data-loader 查看。

**Comment by fengmk2** [comment]
https://npmmirror.com/package/@kanaries/web-data-loader

有的啊

**Comment by ObservedObserver** [comment]
这个包线上npmmirror挂了挺久的，一直是404。线上故障，建议排查一下你们的服务器日志？

**Comment by fengmk2** [comment]
如果你发现没有同步，请手动同步。我们没法保证100%自动同步。

**Comment by ObservedObserver** [comment]
和同步没有关系。搜索包，页面会404，但此前这个包一直是好的，昨天下午突然就变成404了。

这种情况下根本没办法手动同步。

**Comment by fengmk2** [comment]
可以看首页 https://npmmirror.com/ ，有同步方法介绍。
