### ISSUE TITLE
description 信息问题

### ISSUE THREAD

**Issue by atian25** [cnpm/cnpmcore#223]
https://registry.npmjs.org/egg 响应的 description 是 `A web framework's framework for Node.js`

https://registry.npmmirror.com/egg 响应不正常，description 是 `A resources proxy tools for engineer`

https://registry.npmmirror.com/egg/2.35.0 响应正常

**Comment by fengmk2** [comment]
我修复一下，大概知道什么地方漏了。

**Comment by fengmk2** [comment]
需要同步 latest 的字段。
![image](https://user-images.githubusercontent.com/156269/166643076-c616d9e8-6452-40ba-aad1-8a5727305c2c.png)

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/166695198-29e795bb-629b-45c4-b184-a0f713dd7775.png)
