### ISSUE TITLE
create package 默认 isPrivate: true 会导致 admin 没有办法给任意包增加 owner

### ISSUE THREAD

**Issue by laibao101** [cnpm/cnpmcore#225]
根据测试， admin 用户执行 npm owner add **，会报错。原因是 isPrivate: true。 所以这里并没有行成闭环。

https://github.com/cnpm/cnpmcore/blob/main/app/port/controller/package/SavePackageVersionController.ts#L198

![image](https://user-images.githubusercontent.com/17879221/166913493-64c6f9e4-eb88-4a79-89d2-baf7f541abfe.png)

https://github.com/cnpm/cnpmcore/blob/main/app/port/UserRoleManager.ts#L109

![image](https://user-images.githubusercontent.com/17879221/166913668-a7d8567a-d9ce-4d05-bb99-ab5ae79e80a7.png)

**Comment by fengmk2** [comment]
只有发布到 cnpmcore 的包才能设置 owner。npm 同步的包不允许被添加 owner 的。

**Comment by laibao101** [comment]
> 只有发布到 cnpmcore 的包才能设置 owner。npm 同步的包不允许被添加 owner 的。

这个逻辑没问题：通过cnpmcore发布的包才能通过超过 超管或owner 本人来添加 owner。
现在的问题是，就是通过cnpmcore 发布的包，但是发现 超管 没有办法添加owner。
isPrivate 设置为 true， 然后在 requiredPackageMaintainer 方法中， if (!pkg.isPrivate) {} ，很明显这里 if 分支走不进来的。 所以这算是一个逻辑上的缺陷吗？

**Comment by fengmk2** [comment]
可以来提交一个 pr 修复。
