### ISSUE TITLE
请问是否支持采购？

### ISSUE THREAD

**Issue by hezhoushuai** [cnpm/cnpmcore#229]
我们公司想采购一套成品，请问提供这个服务吗

**Comment by fengmk2** [comment]
直接购买阿里云的服务即可 https://www.aliyun.com/product/yunxiao/packages?spm=5176.19720258.J_3207526240.20.e9392c4aQZcNUR&scm=20140722.S_function@@product@@73647._.ID_function@@product@@73647-RL_npm-LOC_bar-OR_ser-V_2-P0_0

**Comment by hezhoushuai** [comment]
我们是纯内网环境，要支持离线部署，云用不了呀😂
