### ISSUE TITLE
How do I configure to synchronize only the last few versions?

### ISSUE THREAD

**Issue by vsme** [cnpm/cnpmcore#230]
I set `syncMode:all` to download all online versions, but only want to synchronize the last few versions in the library since they are for Intranet use. For example, the latest three versions, I want to know how to configure.

**Comment by vsme** [comment]
想知道如何设置同步npm库中的最后几个版本，比如 `lodash` 有 114 个版本，只想要最后三个版本。

**Comment by kkaaddff** [comment]
关于 syncMode 的疑问：
 目前 syncMode 只支持 none ｜ all 两种模式。这两个模式都遇到了一些问题：
1.  不希望 同步所有的包，占据了很多服务器资源，并且同步起来很慢。
2. 设置为none的话，安装时所有的公网包都会 redirect，但是就去年，cnpm源就发生过几次服务不可用的情况。

期望：我们内网部署，希望可以有一种被动式的缓存模式，即安装过的包（版本）缓存一份，再次安装时直接使用本地cache，

**Comment by fengmk2** [comment]
@kkaaddff 可以来贡献这种规则的 syncMode，我觉得合理的。

**Comment by kkaaddff** [comment]
> @kkaaddff 可以来贡献这种规则的 syncMode，我觉得合理的。

好的，有空闲了来做

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/pull/337 支持 exists 模式了。
