### ISSUE TITLE
从老的cnpmjs.org仓库同步时，出现文件名过长导致包下载失败

### ISSUE THREAD

**Issue by coolyuantao** [cnpm/cnpmcore#242]
cnpmjs.org 中有一段逻辑是给 `dist.tarball` 添加 `other_urls`，详情可看这里：https://github.com/cnpm/cnpmjs.org/commit/d1fe6cede7b5a082eabfe9eb94225c9af9399e62
 但这个逻辑带来的一个副作用 URL 的地址长度比较长，特别是一些私有包，包名跟版本号都比较长

在这个情况下，新的cnpmcore在同步时，会把 basename 作为文件真实名称并保存在文件系统上，但是文件系统一般对文件名都有长度限制，比如：`getconf NAME_MAX /` 返回的是255

// 把 `tarball` 作为 `filename`
https://github.com/cnpm/cnpmcore/blob/ac79e540b03fb8a595966ccaaa5d28744b93e5c9/app/core/service/PackageSyncerService.ts#L460-L475

// `basename`的结果不对
https://github.com/cnpm/cnpmcore/blob/ac79e540b03fb8a595966ccaaa5d28744b93e5c9/app/common/FileUtil.ts#L9-L15

最终导致的结果是`tarball`形如下面的包都无法同步：
`http://r.cnpmjs.org/@cnpmtest/testmodule-show/download/@cnpmtest/testmodule-show-1.1.0.tgz?bucket=us1&other_urls=http%3A%2F%2Fr.cnpmjs.org%2F%40cnpmtest%2Ftestmodule-show%2Fdownload%2F%40cnpmtest%2Ftestmodule-show-1.1.0.tgz`

**Comment by fengmk2** [comment]
@coolyuantao Thanks a lot!
