### ISSUE TITLE
RFC：支持基于 cnpmcore 进行二次开发

### ISSUE THREAD

**Issue by killagu** [cnpm/cnpmcore#244]
# 背景
需要对 cnpmcore 进行一些定制独立部署或者与现有系统集成，已现有 npm 包的方式并不方便。期望有一种更加自然的方式，进行二次开发。基于  [tegg 框架](https://github.com/eggjs/tegg) 会是一个不错的选择，可以将 cnpmcore 内部的 module 集成到应用内部，即可使用，无缝启动。

# 框架改造

目前 [tegg 框架](https://github.com/eggjs/tegg) 只支持项目内部的 module，比如说

```json
[
  { "path": "../app/modules/foo" }
]
```

但是 cnpmcore 以 npm 包形式进行分发，因此并不能使用这种 path 的模式。

需要支持一下模式。

```json
[
  { "pkg": "cnpmcore/port" }
]
```

# cnpmcore 适配
## package.json 改造

cnpmcore tsc 构建目录为 dist，需要配置 typings 和 exports 来使 ts 和 `require` 能正常工作。

```json
{
  "typings": "./dist/app",
  "exports": {
    "./common": "./dist/app/common/package.json",
    "./common/*": "./dist/app/common/*.js",
    "./core": "./dist/app/core/package.json",
    "./core/*": "./dist/app/core/*.js",
    "./port": "./dist/app/port/package.json",
    "./port/*": "./dist/app/port/*.js",
    "./repository": "./dist/app/repository/package.json",
    "./repository/*": "./dist/app/repository/*.js",
    "./schedule": "./dist/app/schedule/package.json",
    "./schedule/*": "./dist/app/schedule/*.js"
  },
}
```

## 架构改造
cnpmcore 中的基础设施的接口和实现是写在一起的。以 `NFSAdapter` 举例，依赖了 `NFSClientAdapter` 实现，如果二次开发时需要替换基础设施依赖，直接启用 `common` 模块是无法进行替换的，因此需要将实现部分单独拆出一个实现，命名为 `infra` 模块。

## 对象生命周期改造
现在 cnpmcore 中部分对象的生命周期为单例，比如说 `QueueAdapter`，其依赖了 `redis`，但是在分布式系统中，单例实现并不适合实现追踪，因此会将其改造成 `ContextProto`。

**Comment by fengmk2** [comment]
LGTM！！！

**Comment by fengmk2** [comment]
从年初的 egg 开源应用模糊地使用 module 方式整合到企业内部应用，到现在的更清晰的细节，相信未来基于 egg 的应用会有更多的复用机会。

**Comment by fengmk2** [comment]
https://github.com/cnpm/r.cnpmjs.org 例子
