### ISSUE TITLE
RFC: 是否考虑支持 cnpm.org 原有的 /-/all/since 和 /-/all/static/today.json 等接口

### ISSUE THREAD

**Issue by jsjzh** [cnpm/cnpmcore#247]
## 描述

1. 基于 cnpm.org 私有化部署的项目，同步逻辑使用的是 `/-/all/since` 接口，但发现接口无法调通了，返回 404
2. 发现 cnpmcore 并未提供该接口，例：https://registry.npmmirror.com/-/all/since?stale=update_after&startkey=1407255748643
3. 转而去尝试 npmjs 的接口
  1. https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407255748643 返回空数组
  2. https://registry.npmjs.org/-/all/static/today.json 返回 { "message": "deprecated" }
4. 查看了私有化部署的项目同步时间停留在 2022-01-30 00:00:04，之后都未成功进行同步

cnpm.org 的接口文档描述如下：https://github.com/cnpm/cnpmjs.org/blob/master/docs/registry-api.md#list-packages-since-from-a-update-time

cnpm.org 对应接口如下：https://github.com/cnpm/cnpmjs.org/blob/master/controllers/registry/package/list_since.js#L11

## 问题

cnpmcore 是否考虑增加 `/-/all/since` 和 `/-/all/static/today.json` 接口的支持，这可以帮助基于 cnpm.org 私有化部署的公司正常同步

**Comment by fengmk2** [comment]
无法提供了。
