### ISSUE TITLE
Incorrect tarball url for uglify-es@3.3.10

### ISSUE THREAD

**Issue by bianjp** [cnpm/cnpmcore#256]
The tarball url for uglify-es@3.3.10 returned by npmmirror.com is 
`https://registry.npmmirror.com/uglify-es/-/uglify-es-3.3.9.tgz` (note the version number in url is 3.3.9 instead of 3.3.10).

* https://registry.npmmirror.com/uglify-es -> https://registry.npmmirror.com/uglify-es/-/uglify-es-3.3.9.tgz
* https://registry.npmjs.org/uglify-es -> https://registry.npmjs.org/uglify-es/-/uglify-es-3.3.10.tgz

I tried https://npmmirror.com/sync/uglify-es several times but nothing helps.

In addition, previously https://registry.npmmirror.com/uglify-es/-/uglify-es-3.3.10.tgz returned 404, but currently it returns the same file as 3.3.9 (not sure whether it's caused by `https://npmmirror.com/sync/uglify-es`).

**Comment by fengmk2** [comment]
⠋ [uglify-es@3.3.10] use uglify-es@3.3.9 instead, reason: see https://github.com/mishoo/UglifyJS2/issues/2896

**Comment by bianjp** [comment]
Although 3.3.9 should be used, but as a mirror, shouldn't npmmirror.com return the same content as official npm registry?

Otherwise it might break some projects when they switch between registries without regenerating `yarn.lock` (Yarn berry).
