### ISSUE TITLE
cnpm卡在install.js的下载二进制文件过程中

### ISSUE THREAD

**Issue by cnmission** [cnpm/cnpmcore#263]
最近偶然发现有执行cnpm安装某些包时一直卡在build fresh packages阶段。经过源码分析，调用栈跟踪，发现是卡在post scripte执行过程中的二进制文件下载。比如安装optipng，执行post script阶段，会去https://cdn.npmmirror.com/binaries/optipng-bin/v7.0.1/vendor/macos/optipng
下载optipng这个文件，调用栈显示卡在获取过程中一直没有进展，但是手动下载是正常的。下图1是执行卡住的地方，下图2是正常执行的调用栈和卡住的调用栈对比。（另外发现一个有意思的现象，卡巴斯基扫描yarn cache文件会后会很容易复现此问题，并且卡住后退出卡巴斯基会立即导致卡住的node进程退出）
环境：mac os 10.15.7 (19H15)
cnpm -v
cnpm@8.1.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.17 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@18.2.0 (/usr/local/Cellar/node/18.2.0/bin/node)
npminstall@6.2.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local/Cellar/node/18.2.0 
darwin x64 19.6.0 
registry=https://registry.npmmirror.com

<img width="824" alt="image" src="https://user-images.githubusercontent.com/109270071/178917731-82a090c9-33a3-4def-a56d-71dde847b9e3.png">
<img width="1744" alt="image" src="https://user-images.githubusercontent.com/109270071/178918140-45c4f7b3-6603-4e72-83a3-ac7f4d459534.png">

**Comment by atian25** [comment]
> 卡巴斯基扫描yarn cache文件会后会很容易复现此问题

没太看懂这块， cnpm 没用 yarn cache 的。

关掉杀毒软件还能复现么？

**Comment by cnmission** [comment]
> > 卡巴斯基扫描yarn cache文件会后会很容易复现此问题
> 
> 没太看懂这块， cnpm 没用 yarn cache 的。
> 
> 关掉杀毒软件还能复现么？

只是说：用卡巴斯基扫描yarn cache 之后，会很容易复现此问题，并不知道两者之间是否有关联还是巧合。 牵扯上卡巴斯基主要是注意到，卡住的时候退出卡巴斯基，马上就会导致卡住的node进程退出（也是不知道两者是否有关联）。

关掉卡巴斯基后，还没有复现过。

怀疑1（只是猜测）: cnpmmirror有某种网络限制策略，（将下载地址换成自己建的服务器，同样有卡住的情况）；
怀疑2：可能公司网络有某种策略；

应对方案：
1）可以通过--ignore-scripts 参数跳过 post install script阶段；但是不知道有什么影响；
2）--network-timeout设置超时时间，超时失败会执行本地源码编译；  但是超时参数--network-timeout并没有对 post install script阶段生效；
下一步动作：
1）抓包观察网络方面是否有什么线索；
2）找Linux环境，尝试复现，并分析调用栈；

或者大佬有更好的建议，帮忙分析一下（如果卡住了，需要怎么分析卡住的位置和原因）

**Comment by cnmission** [comment]
结贴：
1）本帖主要目的是找到一种方法能看到yarn或者cnpm在安装时一直没有进度是卡在哪里了；——可以通过strace调用栈看到系统调用来确认是否仍在执行以及执行的类型（下载还是编译）；
2）本帖遇到的卡住分两个原因：a.本地环境卡住，高度怀疑是杀软做了拦截，已经知会it做了白名单；b.CI 环境卡住，有些模块的post script阶段需要国外网下载一些文件导致（增加代理或者确认下载地址是否可以用环境变量来设置，或者用淘宝源（对硬编码的地址做了优化，改成了淘宝源））
3）遗留问题：准备搭建一套环境来识别模块安装时需要访问的所有地址以确认是否存在网络问题；

**Comment by atian25** [comment]
第二点参考 https://github.com/cnpm/cnpmcore/pull/239/files

**Comment by cnmission** [comment]
> 第二点参考 https://github.com/cnpm/cnpmcore/pull/239/files ，比较常用的大包可以类似提 PR 给 npmmirror 做镜像

ok, 3Q
