### ISSUE TITLE
私有化部署时、npm存储目录能否选择本地磁盘、这样部署的方式就会多样化

### ISSUE THREAD

**Issue by flfps** [cnpm/cnpmcore#265]

**Comment by atian25** [comment]
你存储在本地磁盘怎么做负载均衡？机器出问题后如何替换容器？

**Comment by flfps** [comment]
在采用本地磁盘部署的时候已经考虑了磁盘备份的问题

**Comment by atian25** [comment]
oss 不值钱啊，为啥要搞本地磁盘的方案呢

**Comment by fengmk2** [comment]
单机部署稳定性不够，我们不会考虑。
你可以咨询实现一个 nfs。
参考 https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide 接口约定。
