### ISSUE TITLE
Prisma 4.0/4.1对应Binary没有同步过来

### ISSUE THREAD

**Issue by oliverzy** [cnpm/cnpmcore#270]
这个版本是7月18号发布的

官方地址：https://prisma-builds.s3-eu-west-1.amazonaws.com/?delimiter=/&prefix=all_commits/8d8414deb360336e4698a65aa45a1fbaf1ce13d8/

Mirror对应地址为空：https://registry.npmmirror.com/binary.html?path=prisma/all_commits/8d8414deb360336e4698a65aa45a1fbaf1ce13d8/

另外4.0版本da41d2bb3406da22087b849f0e911199ba4fbf11也没有同步过来看上去

同步每一个commit感觉数据量太高，也没必要，最好是只同步Prisma发布版本的commit
![image](https://user-images.githubusercontent.com/1321817/180629843-4bfd2ec5-5140-433a-a115-769f3f917320.png)

这个不知道能不能做到

**Comment by fengmk2** [comment]
Prisma 的 binary 没有找到合适的同步规则。
