### ISSUE TITLE
sharp libvips v latest 同步缺失

### ISSUE THREAD

**Issue by magicdawn** [cnpm/cnpmcore#315]
- https://github.com/lovell/sharp-libvips/releases/tag/v8.13.1
- https://registry.npmmirror.com/binary.html?path=sharp-libvips/v8.13.1/

![image](https://user-images.githubusercontent.com/4067115/190884948-daab92d1-40d1-4e9f-82fa-c50258004dc2.png)

找了一下， binary 貌似没有像 package 一样的同步接口
https://github.com/cnpm/cnpmcore/blob/main/app/port/controller/BinarySyncController.ts

**Comment by fengmk2** [comment]
晚点会操作重复同步一次

**Comment by fengmk2** [comment]
已经重新同步完成
![image](https://user-images.githubusercontent.com/156269/191929740-c6d59212-7c1a-481a-ab28-3edd7409f8e7.png)
