### ISSUE TITLE
修改web展示首页

### ISSUE THREAD

**Issue by johnzhu12** [cnpm/cnpmcore#319]
原来老的[cnpmjs.org](https://github.com/cnpm/cnpmjs.org)，
起来一个http://127.0.0.1:7002，
是web展示，一个是7001是仓库地址，我现在起了这个
[cnpmcore](https://github.com/cnpm/cnpmcore)，只看到有7001

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11485619/191912136-1149d26c-03af-4600-b0ef-c63f4e052aaf.png">

目前我们的需求是要改下web首页，来展示包的list列表，这个貌似老的就是修改那个markdown文档页面。

这个用egg+ts重写的新版没有web吗，还有我要定制化web的话，有对应的指导文档和api文档么，还是只能自己看着改

谢谢

**Comment by fengmk2** [comment]
cnpmcore 目前只有 registry 功能，没有 web 功能。

**Comment by johnzhu12** [comment]
好的，了解，感谢回复
