### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#33]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS

这样后续 Web 应用可以前后端分离，任何前端都可以基于 registry api 做他的个性化 Web。

- [x] CORS
- [ ] user token 支持 JSONWebToken，这样用户认证也支持了。https://jwt.io/introduction

**Comment by fengmk2** [comment]
jws https://github.com/auth0/node-jws

**Comment by barretlee** [comment]
前期还是加一个白名单管控比较好，一方面是控制质量，另一方面也能够了解场景，避免重复建设。

**Comment by fengmk2** [comment]
> 前期还是加一个白名单管控比较好，一方面是控制质量，另一方面也能够了解场景，避免重复建设。

回复没看懂。。。

**Comment by fengmk2** [comment]
Test online:
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fr.cnpmjs.org%2Fcors&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by fengmk2** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
