### ISSUE TITLE
硬件资源如何配置才合理？

### ISSUE THREAD

**Issue by laoboxie** [cnpm/cnpmcore#331]
我在本地做测试的时候，发现同步包的速度有点慢，大约一小时同步200个npm包左右，按照这个速度，同步所有包太久了。

1、请问大家同步所有包（220W+个npm包）用了多久？如何同步所有包？

2、请问大家使用 cnpmcore，使用的硬件资源是怎么样的？
- 使用多少台机器？多少 C 多少 G？
- 使用的 mysql 是多少 C 多少 G？
- 使用的 redis 是多少 G？
- 配置的 syncPackageWorkerMaxConcurrentTasks 数量是多少？

**Comment by killagu** [comment]
1. 取决于集群规模，我们使用 5 台 4C8G 机器在一周内可以同步完
2. mysql 和 redis 使用的是云资源
3. syncPackageWorkerMaxConcurrentTasks 可以配置为 2，再大 CPU 可能被打满了

**Comment by laoboxie** [comment]
> 1. 取决于集群规模，我们使用 5 台 4C8G 机器在一周内可以同步完
> 2. mysql 和 redis 使用的是云资源
> 3. syncPackageWorkerMaxConcurrentTasks 可以配置为 2，再大 CPU 可能被打满了
----
感谢你的答复。
关于第3点的syncPackageWorkerMaxConcurrentTasks，我看cnpmcore默认配置是10，这里设置为2，是不是有点太小了？
另外，cnpmcore `npm run start`是否默认是启动 egg 的多进程模型？

**Comment by fengmk2** [comment]
在初始化阶段可以将 syncPackageWorkerMaxConcurrentTasks 设置足够大。
