### ISSUE TITLE
cnpm.org 升级是否直接平替？

### ISSUE THREAD

**Issue by xuezier** [cnpm/cnpmcore#334]
已经使用 cnpmjs.org 跑了很长时间，升级 cnpmcore 是否直接服务切换即可？还是有其他升级需要注意的，有升级手册吗？

**Comment by fengmk2** [comment]
no，cnpmcore 和 cnpmjs.org 是两个完全不一样的应用。你可以新建一个 cnpmcore，去老的 cnpmjs.org 同步。
