### ISSUE TITLE
希望能支持 syncByInstall 功能

### ISSUE THREAD

**Issue by laoboxie** [cnpm/cnpmcore#335]
看到近期支持了 exist 模式，这个模式能较大地减少对象存储的成本，很赞！但是缺少 syncByInstall 功能。
在这种情况下，当缺少某一个包 bagA 的时候，会直接报错，需要手动同步。
往往存在这样的一个问题：当你手动同步 bagA，需要等到 bagA 同步完成，再重新安装，这个时候，经常出现 bagA 的直接依赖或者间接依赖也没有安装的情况，而且这个依赖链路很多时候很长，所以需要同步多次，等待很久。
所以希望能支持 syncByInstall 功能，来解决自动同步和安装失败等情况。

**Comment by fengmk2** [comment]
现在不存在会直接 redirect 到源站的。

**Comment by laoboxie** [comment]
> 现在不存在会直接 redirect 到源站的。

看起来自动同步和 redirect 的逻辑是被移除了（https://github.com/cnpm/cnpmcore/pull/50/files#diff-97cbafa75ed0bae6a1f0a2df0676c00f56b9cf8944b04ddb82d6dd0ab141961f）
想了解下被移除的原因

**Comment by fengmk2** [comment]
@laoboxie 应该是 sync exists 模式实现的时候不够完整，漏洞了 redirect 逻辑，可以来修复一下 https://github.com/cnpm/cnpmcore/pull/275

**Comment by fengmk2** [comment]
@coolyuantao 可以继续看看这个问题？

**Comment by coolyuantao** [comment]
好，我改下

**Comment by laoboxie** [comment]
我这边已经支持了 syncByInstall 模式，要不我来提个 PR？

**Comment by coolyuantao** [comment]
@laoboxie 你都实现了那你来吧，我也要周末才比较有时间看看

**Comment by coolyuantao** [comment]
看了下逻辑，在 none 跟 exist 模式下应该都要重定向
https://github.com/cnpm/cnpmcore/blob/305175ab5fcdc3ad3b60055d45cfcacb23065a80/app/port/controller/AbstractController.ts#L59-L62

@fengmk2 另外还有一个场景看下要不要一起处理，即如果某个包存在，但安装时某个版本不存在，是否这时也自动重定向。比如：存在一个包A，当前已同步的仅为1.0版本。如果直接安装2.0版本时会直接报错，不会走重定向这个逻辑
https://github.com/cnpm/cnpmcore/blob/305175ab5fcdc3ad3b60055d45cfcacb23065a80/app/port/controller/package/DownloadPackageVersionTar.ts#L47-L50

**Comment by fengmk2** [comment]
版本不存在无法判断的，只有包不存在的时候可以做 302
