### ISSUE TITLE
希望能够提供下载数据版本过滤

### ISSUE THREAD

**Issue by tyaqing** [cnpm/cnpmcore#336]
当我请求
https://registry.npmmirror.com/downloads/range/2022-04-17:2022-10-17/react
我看到数据结构包含了历史版本数据
<img width="438" alt="image" src="https://user-images.githubusercontent.com/11229306/196205969-a2eed27b-e1f6-40e5-bdde-9abf6c1f38e8.png">

可以像npmjs提供综合数据,或者能不能提供版本过滤的query呢
https://api.npmjs.org/downloads/range/2022-04-17:2022-10-17/react

**Comment by fengmk2** [comment]
服务端没有计算能力，你在本地计算即可。
