### ISSUE TITLE
镜像站近两周没有同步了诶

### ISSUE THREAD

**Issue by SevenOutman** [cnpm/cnpmcore#339]
镜像站显示上次同步时间是 12 天前了，请问是出了什么状况吗？

<img width="565" alt="image" src="https://user-images.githubusercontent.com/8225666/197161441-68b89792-a24d-4bf3-bc74-210b2b7b1a1a.png">

**Comment by fengmk2** [comment]
如果出现版本没同步，请手动执行同步。
