### ISSUE TITLE
cnpmcore 存储支持 s3 吗

### ISSUE THREAD

**Issue by yuantongkang** [cnpm/cnpmcore#353]

**Comment by fengmk2** [comment]
目前不支持，默认实现了阿里云 oss 和社区贡献的腾讯云存储
S3 你可以参考 https://github.com/cnpm/cnpmcore/blob/main/app/infra/NFSClientAdapter.ts 实现。

**Comment by hezhengxu2018** [comment]
[s3-cnpm](https://github.com/QubitProducts/s3-cnpm)这个项目还可以用吗？

**Comment by fengmk2** [comment]
得将里面的 generator function 改成 async function https://github.com/QubitProducts/s3-cnpm/blob/master/s3-cnpm.js

**Comment by hezhengxu2018** [comment]
发布了两个依赖[s3v2-cnpmcore](https://github.com/hezhengxu2018/s3v2-cnpmcore)、[s3-cnpmcore](https://github.com/hezhengxu2018/s3-cnpmcore)区别是前者用的是aws-sdk的2.x，在生产下需要设置环境变量：
```shell
AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1
```
后者用的是最新的@aws-sdk/client-s3，nodejs的最低要求是18。

两个依赖的配置是在原sdk原有配置的基础上添加了bucket的配置项，具体请参考各自的官方文档。

两者都处于基本可用的状态，但是s3没有appendBytes的方法，目前是通过读取原有buffer添加新内容后再次上传的，性能不太好。如果是七牛的S3接口短时间内多次append会有问题，第2次读取的内容有概率是第0次的内容。七牛那边给的反馈是涉及到了分布式存储的高可用快响应的数据服务缓存，数据处理有ms级延时。内网部署的对象存储没有这个问题。如果有上述情况七牛的建议是需要在下次读取前等待1000ms，需要自己改造一下，但是性能就更差了。

**Comment by hezhengxu2018** [comment]
两个插件都添加了新的配置项disableURL，因为七牛的S3接口不支持匿名访问，使用pre-signed URL又会使url函数返回的是一个Promise。启用后url将直接是一个undefined，使用createDownloadStream返回存储对象。这样应该就可以直接在七牛上使用，不用再单独包装一个adaper了。

**Comment by baxtergu** [comment]
我试了下用 [s3-cnpmcore](https://github.com/hezhengxu2018/s3-cnpmcore) 这个包来做 cnpmcore 对象存储 NFSClient，测试在私有部署的 s3 协议兼容对象存储服务上生成了100gb的数据，暂未发现太大问题。

**Comment by fengmk2** [comment]
> 我试了下用 [s3-cnpmcore](https://github.com/hezhengxu2018/s3-cnpmcore) 这个包来做 cnpmcore NFSClient，测试在私有部署的 s3 协议兼容对象存储服务上生成了100gb的数据，暂未发现太大问题。

厉害，我整理到官方推荐的 nfsclient 里面去。

**Comment by baxtergu** [comment]
> > 我试了下用 [s3-cnpmcore](https://github.com/hezhengxu2018/s3-cnpmcore) 这个包来做 cnpmcore NFSClient，测试在私有部署的 s3 协议兼容对象存储服务上生成了100gb的数据，暂未发现太大问题。
> 
> 厉害，我整理到官方推荐的 nfsclient 里面去。

刚试了下新加的 unpkg 能力，好像这个 s3 的有点问题

**Comment by baxtergu** [comment]
看了下，s3 的 adapter 貌似读取文件没什么问题，但是单个文件请求始终返回的都是空对象

**Comment by baxtergu** [comment]
s3client关联配置
    config.nfs.client = new S3Client({
      forcePathStyle: true,
      disableURL: true,
    });

**Comment by hezhengxu2018** [comment]
@aws-sdk/client-s3这个sdk对流的操作需要node18的支持。16需要用s3v2-cnpmcore，用的是老的aws的sdk。

**Comment by baxtergu** [comment]
> @aws-sdk/client-s3这个sdk对流的操作需要node18的支持。16需要用s3v2-cnpmcore，用的是老的aws的sdk。

我用的node18+@aws-sdk/client-s3  可读流没法被 egg 框架正常转换，是不是egg的问题？

**Comment by hezhengxu2018** [comment]
我晚点试一下这个新功能看看，两边的单测是一样的不应该会有这种问题😵‍💫

**Comment by baxtergu** [comment]
> 我晚点试一下这个新功能看看，两边的单测是一样的不应该会有这种问题😵‍💫

经尝试，加上下面的，基于 aws v3 sdk 的 createDownloadStream 就正常了。

```
 const webStream = (await this.s3.getObject({ Bucket: this.config.bucket, Key: _key })).Body?.transformToWebStream();
 // @ts-ignore
return Readable.from(webStream);
```

另外吐槽一下，aws-sdk 里 `transformToWebStream()` 这个返回的类型定义是错的，应该是 WebStream 类型，而不是 ReadableStream，只能 ignore 一下了。

**Comment by hezhengxu2018** [comment]
s3-cnpmcore发布了1.1.2版本，s3v2的应该没有这个问题。还没在实际项目里试验这个功能，有问题的话再撤销发布这个版本

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmjs.org/wiki/NFS-Guide#present-storage-wrappers 添加到 wiki
