### ISSUE TITLE
npmmirror 提供了错误的包版本导致完整性校验不通过

### ISSUE THREAD

**Issue by yfdyh000** [cnpm/cnpmcore#371]
https://cdn.npmmirror.com/packages/graceful-fs/4.2.5/graceful-fs-4.2.5.tgz 实际提供了4.2.4版本。
正确版本 https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.5.tgz
不确定是否 https://npmmirror.com/package/graceful-fs/v/4.2.5 为deprecated并有某种特性所致。

此问题导致使用此镜像时，https://github.com/zotero/pdf.js 的npm install始终无法通过，日志出现：
```
npm WARN old lockfile Could not fetch metadata for graceful-fs@4.2.5 Error: Integrity checksum failed when using sha512: wanted sha512-kBBSQbz2K0Nyn+31j/w36fUfxkBW9/gfwRWdUY1ULReH3iokVJgddZAFcD1D0xlgTmFxJCbUkUclAlc6/IDJkw== but got sha512-WjKPNJF79dtJAVniUlGGWHYGz2jWxT6VhN/4m1NdkbZ2nOsEF+cI1Edgql5zCRhs/VsQYRvrXctxktVXZUkixw==.
```

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/graceful-fs/4.2.5
![image](https://user-images.githubusercontent.com/156269/210192647-bb91affd-9f7b-4d47-8d17-9559e1b65e9e.png)

已经恢复。
