### ISSUE TITLE
尝试使用 airplane 搭建 cnpmcore 的 web 前台查询页面

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#386]
https://docs.airplane.dev/getting-started/overview

**Comment by Beace** [comment]
@fengmk2 考虑下 ES 么，有个雏形正准备提个搜索推荐的 PR. https://github.com/Beace/npm-search

**Comment by fengmk2** [comment]
@Beace 来吧，补充上搜索太棒了。

**Comment by elrrrrrrr** [comment]
@Beace 

进展如何 😈 

有 ES 搜索接口之后，我们可以实现 https://npm.io/ 的能力了 🚀

**Comment by Beace** [comment]
> @Beace 
> 
> 
> 
> 进展如何 😈 
> 
> 
> 
> 有 ES 搜索接口之后，我们可以实现 https://npm.io/ 的能力了 🚀

差一个PR了😄ཽ

**Comment by Beace** [comment]
@elrrrrrrr 我建议 cnpm 可以搞个类似 npm 的 rfcs，派专人跟进，有相关的 schedule，避免大家搞了同一套。搜索其实我在公司已经实现了，现在只需要 cnpmcore 化一下就可用，大约需要两周左右。

**Comment by fengmk2** [comment]
@Beace 可以走简单的模式，我马上建一个搜索的 issue，交给你来搞定。

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmweb
