### ISSUE TITLE
binary里面的包同步串了?

### ISSUE THREAD

**Issue by yyjdelete** [cnpm/cnpmcore#416]
https://registry.npmmirror.com/binary.html?path=git-for-windows/
可以看到在文件夹下存在大量来自不知道其他什么包的文件
https://registry.npmmirror.com/binary.html?path=git-for-windows/1.0.0-beta.9/
https://registry.npmmirror.com/binary.html?path=git-for-windows/v24.0.0-nightly.20230127/
https://registry.npmmirror.com/binary.html?path=git-for-windows/zstd-win-x64-1.33.1/
这些错误的文件夹也存在在除git-for-windows外一些其他包中
https://registry.npmmirror.com/binary.html?path=nodejieba/zstd-win-x64-1.33.1/
https://registry.npmmirror.com/binary.html?path=nodejieba/v24.0.0-nightly.20230127/

**Comment by elrrrrrrr** [comment]
@yyjdelete 

https://github.com/cnpm/cnpmcore/pull/378 这个 pr 导致同步路径解析错误

目前不影响下载，近期会开始尝试清理文件 🙏🏻

**Comment by coolyuantao** [comment]
> @yyjdelete
> 
> #378 这个 pr 导致同步路径解析错误
> 
> 目前不影响下载，近期会开始尝试清理文件 🙏🏻

清理文件的脚本可否共享下？

**Comment by elrrrrrrr** [comment]
> 清理文件的脚本可否共享下？

数据量较大，目前是通过一个单独的计算接口来实现的 https://github.com/cnpm/cnpmcore/tree/clean-binary

可以在本地启动 server，将 config.default.js 中的 sourceRegistry 指向实需要清理的 registry 地址 ，访问 `/-/clear/:binaryName` 获取到 sql 脚本。

原理是计算 sourceRegitry 的根目录版本及 binary 配置文件中的版本进行对比。
同时加上 >= '2023-01-21' 的限制。

**Comment by magicdawn** [comment]
为啥有的包只有一部分啊

sharp-libvips

- https://github.com/lovell/sharp-libvips/releases/tag/v8.14.2
- https://registry.npmmirror.com/binary.html?path=sharp-libvips/v8.14.2/

binary 里只有 win 的

**Comment by fengmk2** [comment]
@magicdawn 我重新同步一下。

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=sharp-libvips/v8.14.2/ 恢复。

**Comment by daflyinbed** [comment]
好像还是有脏数据？ https://registry.npmmirror.com/binary.html?path=sharp-libvips/v1.2.244/ 这sharp-libvips 下面还是有swc的包 是我看的地方不对吗
