### ISSUE TITLE
better-sqlite3 镜像损坏

### ISSUE THREAD

**Issue by abcfy2** [cnpm/cnpmcore#419]
自`v8.0.1`版本开始，better-sqlite3镜像损坏了： https://registry.npmmirror.com/binary.html?path=better-sqlite3/v8.0.1/

这个目录下已经没有预编译的二进制包了，而之前一个版本8.0.0则是好的: https://registry.npmmirror.com/binary.html?path=better-sqlite3/v8.0.0/

希望可以修复，谢谢了。

**Comment by fengmk2** [comment]
已经发起重新同步，完成后会同步上来。

**Comment by fengmk2** [comment]
已经恢复。
