### ISSUE TITLE
integrate方式部署的同步速度问题

### ISSUE THREAD

**Issue by hezhengxu2018** [cnpm/cnpmcore#441]
整合模式部署应用的同步速度是否会受到影响？按照文档搭建起来的应用在处理schedule的速度明显下降，在同等配置下integrete模式处理同步任务的速度大约是独立部署速度的一半，应用在检查同步任务的频率上是否会因为整合部署而下降？

另外module.json文件在windows下似乎不能识别出exports导出的路径，必须要用`cnpmcore/dist/app/xxxx`的方式才能在windows下被识别，不知道是不是nodejs的bug。

**Comment by fengmk2** [comment]
> 另外module.json文件在windows下似乎不能识别出exports导出的路径，必须要用cnpmcore/dist/app/xxxx的方式才能在windows下被识别，不知道是不是nodejs的bug。

应该是 tegg 的 bug，可以尝试修复提交 pr 到 tegg。 cc @killagu

**Comment by elrrrrrrr** [comment]
> 在同等配置下integrete模式处理同步任务的速度大约是独立部署速度的一半

是同步任务执行耗时吗？ 可以看看同步日志，预期耗时和独立部署的方式是一样的

**Comment by hezhengxu2018** [comment]
> > 在同等配置下integrete模式处理同步任务的速度大约是独立部署速度的一半
> 
> 是同步任务执行耗时吗？ 可以看看同步日志，预期耗时和独立部署的方式是一样的

记得是处于processing状态下的任务数量是独立部署的一半，明天重新测试一下看看。

**Comment by hezhengxu2018** [comment]
无法复现
