### ISSUE TITLE
registry server listen at undefined:7001, web listen at undefined:7002

### ISSUE THREAD

**Issue by zyy543370785** [cnpm/cnpmcore#447]
搭建了cnpm,无法进行同步，在7002端口查看web网页的同步状态一直为空，没有进行自动同步，在服务启动时有registry server listen at undefined:7001, web listen at undefined:7002的未监听信息，咨询下哪位大佬可以帮忙看看

**Comment by fengmk2** [comment]
能否提供一下复现方式？

**Comment by fengmk2** [comment]
cnpmjs.org 我们已经不再提供技术支持了。
