### ISSUE TITLE
cnpmcore的web查询页面有开发进程么？

### ISSUE THREAD

**Issue by zongzmz** [cnpm/cnpmcore#449]
请问下cnpmcore的web查询页面有开发进程么？

**Comment by fengmk2** [comment]
web 查询页面目前不会在 cnpmcore 实现，欢迎贡献。

**Comment by fengmk2** [comment]
后续 @shinima 会跟进 web 相关功能的进展。

**Comment by elrrrrrrr** [comment]
@zongzmz 

web 页具体有什么需求呀？理论上我们都可以在前端通过接口跨域来调用

Exp: 产物预览 https://github.com/elrrrrrrr/uncap

**Comment by zongzmz** [comment]
@elrrrrrrr 就是跟npmmirror.com 一样的界面

**Comment by fengmk2** [comment]
@elrrrrrrr 有点厉害！https://cnpmweb.vercel.app/package/cnpmcore/home

**Comment by zongzmz** [comment]
@elrrrrrrr 查询出来的应该都是 NPM私有库里面已经存在的应用了吧？

如果不存在的应用 如何进行更新，如何查看更新下载进度？是不是可以增加这个功能需求？ 

>

**Comment by elrrrrrrr** [comment]
如果不存在的应用 如何进行更新，如何查看更新下载进度？是不是可以增加这个功能需求？
----
@zongzmz 可以的，可以做个同步入口。
搜索功能目前使用的是 https://github.com/algolia/npm-search#using-the-public-index 是公网的数据，需要切换到 cnpmcore 自己的 es 上。

**Comment by fengmk2** [comment]
https://web.npmmirror.com/package/supports-color/home 已经上线，准备切流

**Comment by fengmk2** [comment]
代码库 https://github.com/cnpm/cnpmweb

**Comment by fengmk2** [comment]
已经发布 https://npmmirror.com/
