### ISSUE TITLE
cnpmcore默认从哪个registry下载依赖包？能否指定为淘宝的镜像

### ISSUE THREAD

**Issue by washheart** [cnpm/cnpmcore#451]
cnpmcore默认从哪个registry下载依赖包？能否指定为淘宝的镜像

**Comment by washheart** [comment]
是否是修改config.default.ts的“sourceRegistry: 'https://registry.npmjs.org'”

**Comment by fengmk2** [comment]
@washheart 是的，修改 https://github.com/cnpm/cnpmcore/blob/master/config/config.default.ts#L14 sourceRegistry 到 https://registry.npmmirror.com 就能从中国镜像同步。
