### ISSUE TITLE
Support list and view raw files

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#452]
like unpkg https://www.unpkg.com/

- [ ] files list

```
GET /:name/:versionOrTag/files

< cache-control: public, max-age=31536000
```

- [ ] raw file with cache

```
GET /:name/:versionOrTag/files/:filename

< cache-control: public, max-age=31536000
```

- [ ] Query Parameters

`?meta`

file

```json
{
  "path": "/dist/jquery.js",
  "type": "file",
  "contentType": "application/javascript",
  "integrity": "sha384-SCPawFAkxFucxzK6X4Gpg3lmBZqjjmM8ghZCRH8hW4C+k4wCVXFd862J1juShkQ7",
  "lastModified": "Sat, 26 Oct 1985 08:15:00 GMT",
  "size": 292458
}
```

directory

https://unpkg.com/foo@0.0.7/?meta
https://unpkg.com/foo@0.0.7/bin/?meta

```json
{
  "path": "/",
  "type": "directory",
  "files": [
    {
      "path": "/package.json",
      "type": "file",
      "contentType": "application/json",
      "integrity": "sha384-LjyVu9SEqK09n+gJRfcvngZbE2inwUSSohs45oN33FnWohqbHEJwfV4JRANIay9y",
      "lastModified": "Wed, 01 Nov 2017 20:25:16 GMT",
      "size": 527
    },
    {
      "path": "/index.js",
      "type": "file",
      "contentType": "application/javascript",
      "integrity": "sha384-oIed2+jQ4ttf1zy77HoKfkrlBHoIOllAb6N6wiu/R0tbfRHHuPnq3ktKaHGtSCvN",
      "lastModified": "Mon, 30 Oct 2017 23:17:07 GMT",
      "size": 112
    },
    {
      "path": "/README.md",
      "type": "file",
      "contentType": "text/markdown",
      "integrity": "sha384-0rRJbY7oVFbmG4NQlkYX0TuucHOUPI1e7PhVxrlHJ6baFKp0TxD9inkusVlYlfAL",
      "lastModified": "Mon, 30 Oct 2017 23:17:07 GMT",
      "size": 980
    },
    {
      "path": "/bin",
      "type": "directory",
      "files": [
        {
          "path": "/bin/foo.js",
          "type": "file",
          "contentType": "application/javascript",
          "integrity": "sha384-ophM0P8AUxaLQrhigIeeN7rZeQVMHFFBLgfb5+zgzaypl7Mf6EIju9Xz+qyWf8Zn",
          "lastModified": "Wed, 01 Nov 2017 20:21:27 GMT",
          "size": 663
        }
      ]
    },
```

## Cache

> URLs that do not specify a package version number redirect to one that does. This is the latest version when no version is specified, or the maxSatisfying version when a [semver version](https://github.com/npm/node-semver) is given. Redirects are cached for 10 minutes at the CDN, 1 minute in browsers.

```
< cache-control: public, s-maxage=600, max-age=60
```

**Comment by hax** [comment]
我知道了，`files`后面得加斜杠。准确的说是 files 后面如果 path 以 `/` 结尾就是目录的 meta。只不过文件 meta 还是要用 `?meta` 来得到。

**Comment by fengmk2** [comment]
可以显式传递 meta 参数获取元信息，如 https://registry.npmmirror.com/antd/5.4.7/files?meta 和 https://registry.npmmirror.com/antd/5.4.7/files/lib/index.js?meta

/ 是一个 unpkg 的规则，我们 follow 了。

**Comment by fengmk2** [comment]
是要被 @hax 重用了么，开心啊

**Comment by fengmk2** [comment]
> 和 unpkg 的另一个差异是，`:versionOrTag` 不填不会自动取 latest，如果要结合 `files` 使用就必填，填`latest`会重定向。
> 
> 一个问题是 `:versionOrTag` 不支持 semver range。unpkg 是支持的，会自动重定向。

从变量命名可以看到目前只支持 version 和 tag，semver range version 目前还不支持，计算量有点大，怕 cpu 被打挂，就没有支持。

**Comment by hax** [comment]
> 是要被 @hax 重用了么，开心啊

有个项目可能会在前端直接拉package下来，目前用的unpkg，如果cnpm/npmmirror可用的话，感觉稳定性会更好一点？ :P

**Comment by fengmk2** [comment]
> > 是要被 @hax 重用了么，开心啊
> 
> 有个项目可能会在前端直接拉package下来，目前用的unpkg，如果cnpm/npmmirror可用的话，感觉稳定性会更好一点？ :P

嗯，如果 semver range 是强诉求，我看看怎么可以节省 cpu 的方式支持。

**Comment by hax** [comment]
也不算很强的需求。但如果没有就得自己拿整个包的versions列表然后自己算。目前我们项目的代码就是这么干的。但我打算直接用unpkg的能力，可以省这一步，也少一个拿整个包元数据的请求（这个请求也不小）。

**Comment by hax** [comment]
> / 是一个 unpkg 的规则，我们 follow 了。

unpkg对于末尾为`/`现在的行为似乎是 `/:name@:semver/path/` 直接跳转到 `/browse/:name@:version/path/`

**Comment by fengmk2** [comment]
> > / 是一个 unpkg 的规则，我们 follow 了。
> 
> unpkg对于末尾为`/`现在的行为似乎是 `/:name@:semver/path/` 直接跳转到 `/browse/:name@:version/path/`

目前我们还没 web 渲染能力，所以跳 JSON 接口了。

**Comment by fengmk2** [comment]
@killagu 发明了一种神奇高效的 semver range SQL 查询算法，后面 semver range 接口也会被支持。

**Comment by hax** [comment]
semver 有很多神奇语法比如 `range1 || range2` 这种，unpkg 似乎都是支持的。不知道「神奇高效算法」都能支持吗？😜

**Comment by hax** [comment]
由于 https://blog.izs.me/2021/10/my-favorite-npm-commit/ ，`lastModfied`字段在大部分文件是毫无意义的（最顶上的示例中「Sat, 26 Oct 1985 08:15:00 GMT」已经是这样的了）。建议直接去掉，还能省点流量。

**Comment by killagu** [comment]
支持的。semver 会把表达式 parse 成 operator，把 operator 翻译为 sql 的 where 条件是可行的。

**Comment by fengmk2** [comment]
range 接口查询放到 https://github.com/cnpm/cnpmcore/issues/134 跟进

**Comment by hax** [comment]
似乎对于 scoped package 有 bug。

https://registry.npmmirror.com/lodash-es/4.17.7/files/  -> ok
https://registry.npmmirror.com/@types/lodash-es/4.17.7 -> ok
https://registry.npmmirror.com/@types/lodash-es/4.17.7/files -> ERR_TOO_MANY_REDIRECTS
https://registry.npmmirror.com/@types/lodash-es/4.17.7/files?meta -> 404
https://registry.npmmirror.com/@types/lodash-es/4.17.7/files/ -> 404

**Comment by fengmk2** [comment]
> 似乎对于 scoped package 有 bug。
> 
> https://registry.npmmirror.com/lodash-es/4.17.7/files/ -> ok https://registry.npmmirror.com/@types/lodash-es/4.17.7 -> ok https://registry.npmmirror.com/@types/lodash-es/4.17.7/files -> ERR_TOO_MANY_REDIRECTS https://registry.npmmirror.com/@types/lodash-es/4.17.7/files?meta -> 404 https://registry.npmmirror.com/@types/lodash-es/4.17.7/files/ -> 404

https://github.com/cnpm/cnpmcore/pull/479 bugfix 已经合并，我没有发布我的锅，我发一下。

**Comment by elrrrrrrr** [comment]
https://registry.npmjs.org/@types/lodash-es/-/lodash-es-4.14.0.tgz

(⊙o⊙)… 看上去是另一个问题，有些 tgz 包下载之后没有默认的 package 路径

**Comment by fengmk2** [comment]
https://unpkg.com/browse/@types/lodash-es@4.17.0/package.json 缺失 files 字段，这个 tgz 还很有趣，不像是通过 npm cli 发布的，解压处理的第一层目录都不叫 package 目录名。

**Comment by Beace** [comment]
> https://unpkg.com/browse/@types/lodash-es@4.17.0/package.json 缺失 files 字段，这个 tgz 还很有趣，不像是通过 npm cli 发布的，解压处理的第一层目录都不叫 package 目录名，导致这个逻辑判断错误 https://github.com/cnpm/cnpmcore/blob/master/app/core/service/PackageVersionFileService.ts#L73 

yarn publish 的解压不会有 package

**Comment by fengmk2** [comment]
@hax 都修复了。

**Comment by atian25** [comment]
写了个资讯：https://zhuanlan.zhihu.com/p/633904268
