### ISSUE TITLE
 ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time     at emitExperimentalWarning (node:internal/util:224:11)

### ISSUE THREAD

**Issue by zyy543370785** [cnpm/cnpmcore#454]
在部署时运行npm run start，报错如下，请教一下，有解决办法吗？

(node:119144) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at node:stream/web:7:1
    at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
    at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
    at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
    at Function.Module._load (node:internal/modules/cjs/loader:804:15)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/cnpmjs/cnpmcore/node_modules/undici/lib/fetch/response.js:30:53)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)

**Comment by fengmk2** [comment]
node 升级到 >=16 版本。

**Comment by zyy543370785** [comment]
目前node是v17.0.0版本，是否版本过高了

**Comment by zyy543370785** [comment]
当前替换为16.0版本执行会有，但由于不熟悉该代码，不知道怎么调试，希望能指导一下

[egg-scripts] Starting egg application at /cnpmjs/cnpmcore
[egg-scripts] Run node --no-deprecation --trace-warnings --require /cnpmjs/cnpmcore/node_modules/source-map-support/register.js /cnpmjs/cnpmcore/node_modules/egg-scripts/lib/start-cluster {"baseDir":"/cnpmjs/cnpmcore","framework":"/cnpmjs/cnpmcore/node_modules/egg","title":"egg-server-cnpmcore"} --title=egg-server-cnpmcore
[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] Wait Start: 6...
[egg-scripts] tail -n 100 /root/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] 2023-05-04 17:13:00,632 ERROR 46308 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] Error: write EPIPE
[egg-scripts]     at process.target._send (node:internal/child_process:849:20)
[egg-scripts]     at process.target.send (node:internal/child_process:722:19)
[egg-scripts]     at Function.send (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/utils/mode/impl/process/app.js:45:13)
[egg-scripts]     at Object.<anonymous> (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/app_worker.js:40:11)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:988:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[egg-scripts]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[egg-scripts]     at node:internal/main/run_main_module:17:47
[egg-scripts] 2023-05-04 17:13:00,649 ERROR 46231 [app_worker] exit with code:1
[egg-scripts] 2023-05-04 17:13:00,649 ERROR 45999 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,654 ERROR 45851 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,656 ERROR 45858 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,675 ERROR 45816 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,702 ERROR 45774 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] Error: write EPIPE
[egg-scripts]     at process.target._send (node:internal/child_process:849:20)
[egg-scripts]     at process.target.send (node:internal/child_process:722:19)
[egg-scripts]     at Function.send (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/utils/mode/impl/process/app.js:45:13)
[egg-scripts]     at Object.<anonymous> (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/app_worker.js:40:11)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:988:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[egg-scripts]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[egg-scripts]     at node:internal/main/run_main_module:17:47
[egg-scripts] 2023-05-04 17:13:00,718 ERROR 46541 [app_worker] exit with code:1
[egg-scripts] 2023-05-04 17:13:00,734 ERROR 45894 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,735 ERROR 45823 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,737 ERROR 45746 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,748 ERROR 46013 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,754 ERROR 45698 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,762 ERROR 45739 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,775 ERROR 45908 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,800 ERROR 45704 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,801 ERROR 45717 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,810 ERROR 45914 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,825 ERROR 45795 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2023-05-04 17:13:00,827 ERROR 46287 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false

**Comment by zyy543370785** [comment]
比如配置了同步模式为all,报错会有不同，
[egg-scripts] Error: write EPIPE
[egg-scripts]     at process.target._send (node:internal/child_process:849:20)
[egg-scripts]     at process.target.send (node:internal/child_process:722:19)
[egg-scripts]     at Function.send (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/utils/mode/impl/process/app.js:45:13)
[egg-scripts]     at Object.<anonymous> (/cnpmjs/cnpmcore/node_modules/egg-cluster/lib/app_worker.js:40:11)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1108:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:988:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
[egg-scripts]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[egg-scripts]     at node:internal/main/run_main_module:17:47
[egg-scripts] 2023-05-04 17:22:42,551 ERROR 51230 [app_worker] exit with code:1
[egg-scripts] 
[egg-scripts] Start got error, see /root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.

**Comment by zyy543370785** [comment]
目前已解决运行问题，想咨询一下是否有web管理功能，暂未找到相关参考代码

**Comment by zyy543370785** [comment]
网页管理能力较为重要的一环

**Comment by fengmk2** [comment]
web 控制面目前没有做

**Comment by zyy543370785** [comment]
大佬，https://npmmirror.com的数据统计及搜索网页，部署应该参考那部分内容呀
