### ISSUE TITLE
 ERROR 30837 nodejs.Error: [NFSAdapter] Can't use local fs NFS on production env

### ISSUE THREAD

**Issue by lucashaha** [cnpm/cnpmcore#464]
运行npm run start后有这个报错，请问应该如何处理

**Comment by lucashaha** [comment]
git clone https://github.com/cnpm/cnpmcore.git
docker-compose up -d
npm run tsc
npm run start
这是启动的步骤，然后就是报nfs报错

**Comment by hezhengxu2018** [comment]
经过编译后会当成生产环境启动，生产环境需要配置对象存储的参数。直接npm run dev就行了。

**Comment by lucashaha** [comment]
谢谢，确实可以了，这个作为私有仓库如何从官方npm源同步数据？好像没有web页面sync功能

**Comment by hezhengxu2018** [comment]
没有web页面，把配置项syncMode改成all就是从官方源全量同步

**Comment by lucashaha** [comment]
cnpm config set registry http://localhost:7001
然后用cnpm sync husky命令从远端同步包到自己源，有connectimeouterror ，status -1报错，这是因为官网源连不上吗
![image](https://github.com/cnpm/cnpmcore/assets/99971678/0f12da20-caa3-4323-9fe3-bf6a7b1a5ab7)

**Comment by hezhengxu2018** [comment]
可能是，可以查看依赖的同步日志排查问题
