### ISSUE TITLE
cnpmcore自身日志位置是否可以自定义位置？

### ISSUE THREAD

**Issue by JasonBrook97** [cnpm/cnpmcore#465]
在confi.default.ts中配置  
config.logger = {
    dir:'/path/to/logs/'
    enablePerformanceTimer: true,
    enableFastContextLogger: true,
  };
egg的日志会记录到指定位置，但root下还有alinode，master-stderr.log ,和master-stdout.log ,如何把这部分日志也放置在指定位置。

**Comment by fengmk2** [comment]
可以参考 https://www.eggjs.org/zh-CN/core/logger egg 日志文档，有相关配置。

**Comment by Zheaoli** [comment]
实际上这个地方可以衍生出一个特性，是否可以增加一个 shortcut，使用环境变量的方式可以在不改动代码的情况下修改日志输出位置，输出格式这些基本的日志配置？

**Comment by fengmk2** [comment]
@Zheaoli 确实，可以通过环境变量来设置一些关键数据存储配置。
