### ISSUE TITLE
同步数据多了以后，无法启动

### ISSUE THREAD

**Issue by shilucus** [cnpm/cnpmcore#470]
目前我们准备对老版本的cnpm进行升级，使用docker部署到以后发现，数据同步一段时间后（全量同步），服务重启不起来了。

经过排查定位到和磁盘上同步的数据大小有关。

后来在自己电脑上做了测试，磁盘上的数据同步到40G左右的时候就无法正常启动了。

目前使用的是v3.13.2

**Comment by fengmk2** [comment]
本地磁盘存储模式只能用于开发测试，真实要长期运行还是得走云存储。

**Comment by zongzmz** [comment]
走nfs 行么?

**Comment by shilucus** [comment]
> 本地磁盘存储模式只能用于开发测试，真实要长期运行还是得走云存储。

换成oss可以了，谢谢
