### ISSUE TITLE
Direct S3 download URL for prisma will be decomissioned soon.

### ISSUE THREAD

**Issue by miguelff** [cnpm/cnpmcore#472]
Hello, my name is Miguel and work at Prisma.

Recently we migrated our infrastructure for engine file distribution form AWS S3 to Cloudflare R2, as a consequence, `https://prisma-builds.s3-eu-west-1.amazonaws.com/` will cease to work soon.

The thing is R2 doesn't provide a drop-in replacement for all S3 features. One of which is listing the objects as XML. 

I build a simple cloudflare worker to list engine files at `https://list-binaries.prisma-orm.workers.dev/` and would like you to use it instead.  The worker currently returns JSON rather than XML, and supports the `cursor`, `prefix` and `delimiter` [options](https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#r2listoptions)

Could you please give a try and use it instead of the current S3 endpoint? We plan to decomission it really soon.

**Comment by fengmk2** [comment]
@miguelff Thanks for the reminder, we will migrate to the new https://list-binaries.prisma-orm.workers.dev/ API as soon as possible.

**Comment by fengmk2** [comment]
@miguelff https://list-binaries.prisma-orm.workers.dev/?delimiter=/&prefix=all_commits/ the number of results only 10, not the R2 1000 limit by default.
The S3 endpoint will return 1000 by default https://prisma-builds.s3-eu-west-1.amazonaws.com/?delimiter=/&prefix=all_commits/

**Comment by fengmk2** [comment]
https://list-binaries.prisma-orm.workers.dev/all_commits/2452cc6313d52b8b9a96999ac0e974d0aedf88db/darwin-arm64/prisma-fmt.gz the file download url not work

**Comment by miguelff** [comment]
Right the download domain keeps being the official one `binaries.prisma.sh` now pointing to Cloudflare. The URL for the listing serves its specific purpose of listing binaries. I'm off until monday, but happy to help when I'm back!

**Comment by miguelff** [comment]
(example for the asset you provided: https://binaries.prisma.sh/all_commits/2452cc6313d52b8b9a96999ac0e974d0aedf88db/darwin-arm64/prisma-fmt.gz)

**Comment by fengmk2** [comment]
> (example for the asset you provided: https://binaries.prisma.sh/all_commits/2452cc6313d52b8b9a96999ac0e974d0aedf88db/darwin-arm64/prisma-fmt.gz)

Nice :)
