### ISSUE TITLE
同步非 latest 版本时，readme 文件内容获取不正确

### ISSUE THREAD

**Issue by shinima** [cnpm/cnpmcore#481]
https://github.com/cnpm/cnpmcore/blob/9e5e555552716ad26ce6127cb149f2844bedd405/app/core/service/PackageSyncerService.ts#L413-L446

按照这里的逻辑，readme 内容是从 full manifest 中获取的，也就是 latest 版本的内容。     同步非 latest 版本时，readme 的内容会出错。

期望行为： readme 内容应该从对应版本的 manifest 中获取。

以 react 16.14.0 为例...
- 正确的行为：请求 https://registry.npmjs.com/react/-/react-16.14.0.tgz  ，下载压缩包，解压读取 readme 文件内容
- 错误的行为：请求 https://registry.npmjs.com/react  直接获取 readme 内容

**Comment by fengmk2** [comment]
是一个问题，npm registry 是不会返回单个版本的 readme 的，所以这个 readme 是补偿而来。现在有了 unpkg 能，可以直接读取 tgz 里面的 readme 进行补偿了。

**Comment by fengmk2** [comment]
@shinima 来贡献一个？

**Comment by shinima** [comment]
> @shinima 来贡献一个？

最近有点忙，稍晚一会儿来贡献。

**Comment by fengmk2** [comment]
https://registry.npmjs.org/@types/debug 直接有 readme 错误的情况出现了， @shinima 我会接手尽快修复了。

![image](https://github.com/cnpm/cnpmcore/assets/156269/8b2a82d6-fdc5-4af2-b036-6579597ec9fb)

**Comment by fengmk2** [comment]
https://github.com/npm/cli/issues/3904 看起来官方也有类似问题。

**Comment by elrrrrrrr** [comment]
https://registry.npmjs.org/elr-test-read-me

测了一下版本 tag 更新的情况，将 latest 从 1.0.5 切到 1.0.2，readme 字段没有更新，还是 1.0.5 的内容。

registry 返回的信息应该是包维度的，只有 publish 的时候才更新。

packageVersion#readmeDist 是不是可以删了？似乎没有消费场景。
改成统一更新 package#readmeDist ，和 npmjs 逻辑保持一致。
