### ISSUE TITLE
在没有web节面的情况下 如何下载包文件？

### ISSUE THREAD

**Issue by zongzmz** [cnpm/cnpmcore#503]
在没有web节面的情况下 如何下载包文件？

之前cnpmjs的版本有接口可以直接同步 仓库里面没有的包文件下载到nfs，但是新版本改造后暂时没有web界面，so，该如何同步？安装时候 会自动同步？还是需要用接口同步，谢谢

**Comment by elrrrrrrr** [comment]
> 仓库里面没有的包文件下载到nfs

是说触发一个包同步吗？ 
可以安装一下 `cnpm` ，然后执行 `cnpm sync ${pkg} --registry=xxx` 就可以了

**Comment by elrrrrrrr** [comment]
😄 我先关闭这个 issue 了，如果有问题可以继续 reopen
