### ISSUE TITLE
集成模式升级 cnpmcore 依赖启动报错

### ISSUE THREAD

**Issue by baxtergu** [cnpm/cnpmcore#504]
以集成模式将 cnpmcore 集成至一个 tegg 项目，cnpmcore 版本 3.21.0 ts 4.9.5

升级至 3.22.3 版本没有问题，但是升级到下一个版本 3.23.1 就会启动报错如下：

![screen_shot_1686276011448](https://github.com/cnpm/cnpmcore/assets/2825625/2a22c5ac-93b9-4b56-8940-48421a2ca395)

查了下发布记录，似乎跟 #483 的 EggObjectLifecycle -> LifecycleInit 装饰器有关

尝试将 module.json 中的自定义 infra 引入替换成默认的 cnpmcore/infra 也会报同样的错误。

**Comment by elrrrrrrr** [comment]
@baxtergu 

看看 `@eggjs/tegg-lifecycle` 版本是 3.8.0 吗？

**Comment by baxtergu** [comment]
> @baxtergu
> 
> 看看 `@eggjs/tegg-lifecycle` 版本是 3.8.0 吗？

![screen_shot_1686277116023](https://github.com/cnpm/cnpmcore/assets/2825625/c58e66ce-f3fa-442b-ad96-41a34ed0c27e)

我的 tegg 项目都是用 3.8.0 的，但是似乎 cnpmcore 的依赖版本比较低

**Comment by elrrrrrrr** [comment]
是之前锁了依赖吗？ 看上去只要升级到 3.8.0 即可

**Comment by baxtergu** [comment]
@elrrrrrrr 的确是lock文件的锅，我删了重新生成 OK 了。

**Comment by baxtergu** [comment]
关闭
