### ISSUE TITLE
私有部署模式没有拦截非 scoped package 发布

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#508]
![image](https://github.com/cnpm/cnpmcore/assets/156269/fcf99f90-844d-448c-b0f3-90fdae4edad9)

**Comment by elrrrrrrr** [comment]
当前账户是管理员，或者之前发布过这个包吗？
https://github.com/cnpm/cnpmcore/blob/master/app/port/UserRoleManager.ts#L79

![image](https://github.com/cnpm/cnpmcore/assets/5574625/fad78d69-1cc1-488d-9265-70e04f4c9e4e)
本地试了下没重现 🤔

**Comment by fengmk2** [comment]
> 当前账户是管理员，或者之前发布过这个包吗？ https://github.com/cnpm/cnpmcore/blob/master/app/port/UserRoleManager.ts#L79
> 
> ![image](https://user-images.githubusercontent.com/5574625/244929501-fad78d69-1cc1-488d-9265-70e04f4c9e4e.png) 本地试了下没重现 🤔

https://github.com/cnpm/cnpmcore/pull/509/files#r1225793097

**Comment by elrrrrrrr** [comment]
@fengmk2 

按照之前的设计 无 scope 的公网包也允许内部进行覆盖，主要基于一下考虑
1. 公网包可能出现预期外的 unpublish 或者误删除的情况 [ref](https://twitter.com/2009xdf/status/1621453745942036480)
2. 有一些无scope的内网包 [ref](https://registry.npmmirror.com/tnpm)
无 scope 的公网包目前只允许管理员新增，覆盖后也不会再从源进行同步

之前设置了 `allowPublishNonScopePackage` 用以限制普通用户。

|       | 管理员| 普通用户|
|-------|-------|-------|
| 开关打开| ✅ 存量包 | ✅ 存量包|
|       | ✅ 新增包 | ✅ 新增包|
| 开关关闭| ✅ 存量包 | ✅ 存量包|
|       | ✅ 新增包 | ❎ 新增包 |

后续我们修改为管理员也受这个配置限制？

**Comment by fengmk2** [comment]
那先不管了，看起来是 by design
