### ISSUE TITLE
使用SyncMode.exist模式

### ISSUE THREAD

**Issue by zongzmz** [cnpm/cnpmcore#525]
使用SyncMode.exist模式 不会自动下载包与依赖到nfs么？

**Comment by zongzmz** [comment]
或者说 如何修改配置文件 才会在安装包得时候 同步下载自身依赖缓存到nfs？

**Comment by hezhengxu2018** [comment]
你是否在找 #366 ？

**Comment by hezhengxu2018** [comment]
可以启用redirectNotFound和syncNotFound，不过会同时同步这个包的所有版本

**Comment by zongzmz** [comment]
> 可以启用redirectNotFound和syncNotFound，不过会同时同步这个包的所有版本

启用后安装报错E500？

**Comment by hezhengxu2018** [comment]
这样配置应该可以，不过会同步相关依赖的所有版本。报500错误是服务器配置有问题了，先保证后端运行正常再看同步的问题

**Comment by zongzmz** [comment]
> 这样配置应该可以，不过会同步相关依赖的所有版本。报500错误是服务器配置有问题了，先保证后端运行正常再看同步的问题
我本地服务运行正常吧？
![image](https://github.com/cnpm/cnpmcore/assets/6846341/c4510159-37fa-4f14-81d3-1970ad540483)

**Comment by hezhengxu2018** [comment]
那么应该可以正常访问http://127.0.0.1:7001/element-plus,也可以通过这个返回的json找到latest，进而找的对应的tgz文件

**Comment by zongzmz** [comment]
> 那么应该可以正常访问[http://127.0.0.1:7001/element-plus，也可以通过这个返回的json找到latest，进而找的对应的tgz文件，第一次访问地址的时候应该会重定向？然后会开始创建同步任务](http://127.0.0.1:7001/element-plus%EF%BC%8C%E4%B9%9F%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87%E8%BF%99%E4%B8%AA%E8%BF%94%E5%9B%9E%E7%9A%84json%E6%89%BE%E5%88%B0latest%EF%BC%8C%E8%BF%9B%E8%80%8C%E6%89%BE%E7%9A%84%E5%AF%B9%E5%BA%94%E7%9A%84tgz%E6%96%87%E4%BB%B6%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E8%AE%BF%E9%97%AE%E5%9C%B0%E5%9D%80%E7%9A%84%E6%97%B6%E5%80%99%E5%BA%94%E8%AF%A5%E4%BC%9A%E9%87%8D%E5%AE%9A%E5%90%91%EF%BC%9F%E7%84%B6%E5%90%8E%E4%BC%9A%E5%BC%80%E5%A7%8B%E5%88%9B%E5%BB%BA%E5%90%8C%E6%AD%A5%E4%BB%BB%E5%8A%A1)

![image](https://github.com/cnpm/cnpmcore/assets/6846341/3dff014b-1bf5-4277-929b-a1bd4db19045)
实际的结果是这样

**Comment by hezhengxu2018** [comment]
https://github.com/cnpm/cnpmcore/blob/84499bc9f85872e6906cfabbe14ce56a31fd97ca/app/port/controller/AbstractController.ts#L159
https://github.com/cnpm/cnpmcore/blob/84499bc9f85872e6906cfabbe14ce56a31fd97ca/app/port/controller/AbstractController.ts#L167
是的，这里有点问题，两个throw error的地方都没有把allowSync的值传入，导致不会创建同步任务。可以把这个函数的第三个参数都设为ture先，应该可以正常创建任务了

**Comment by zongzmz** [comment]
嗯 我也找到这个地方了~ 都是默认值false

**Comment by zongzmz** [comment]
尽快修复吧

**Comment by zongzmz** [comment]
我修改了
![image](https://github.com/cnpm/cnpmcore/assets/6846341/a19112e2-f226-42e5-b1ea-e53a3c9069e4)
这两个地方的引用 好像还是如此？同步任务好像没创建
![image](https://github.com/cnpm/cnpmcore/assets/6846341/f2d608e8-792c-4984-b2f4-049c98d68f62)

**Comment by hezhengxu2018** [comment]
改完本地试了一下已经可以创建任务了，是不是别的配置有问题

**Comment by zongzmz** [comment]
> 改完本地试了一下已经可以创建任务了，是不是别的配置有问题

你也是改的这两个地方嘛？我跟你改的一样？ 然后方便贴下你的配置信息么？
我的配置是下图
![image](https://github.com/cnpm/cnpmcore/assets/6846341/312a352e-8ded-482d-a35f-d28765f08fea)

**Comment by hezhengxu2018** [comment]
用npm命令行工具访问`GET /:fullname/:versionSpec`、`GET /:fullname`这两个接口的时候是可以创建同步的，不用改也能创建。现在有问题是直接访问tgz文件地址不会创建同步任务，用浏览器不会创建同步任务。

**Comment by zongzmz** [comment]
执行命令 npm install xxx-package 的时候 是不是没有包的情况下 自动去同步？

**Comment by hezhengxu2018** [comment]
会的，npm会先去访问package的索引，不会创建同步任务的是带lock文件的pnpm项目

**Comment by zongzmz** [comment]
@hezhengxu2018 带lock的pnpm项目如何同步?
![image](https://github.com/cnpm/cnpmcore/assets/6846341/6db4acb1-425f-4654-9cb5-81bca8c60bbe)

**Comment by zongzmz** [comment]
> `PUT` http://localhost:7001/-/package/element-plus/syncs 可以用postman去访问这个地址看返回的结果是什么

404 Not Found

**Comment by hezhengxu2018** [comment]
带lock文件的pnpm项目会直接访问tgz地址，现在直接访问tgz的地址只会重定向不会创建任务，如果你已经把那个入参改为true了应该已经会创建任务了

**Comment by zongzmz** [comment]
> 带lock文件的pnpm项目会直接访问tgz地址，现在直接访问tgz的地址只会重定向不会创建任务，如果你已经把那个入参改为true了应该已经会创建任务了

你看看我的配置文件有问题么？跟我弃用了redis有关系么？如果没问题的话 我明天部署带服务器上试试

**Comment by hezhengxu2018** [comment]
还能弃用redis吗？我不知道

**Comment by zongzmz** [comment]
> 还能弃用redis吗？我不知道

哎~ redis的问题
{
    "error": "this.redis.zcount is not a function"
}

**Comment by hezhengxu2018** [comment]
现在只剩使用pnpm安装带lock文件的项目不会创建任务的问题了

**Comment by zongzmz** [comment]
还有个bug，我查了下users的表 有多个keys  删除uk_name就可以了
![image](https://github.com/cnpm/cnpmcore/assets/6846341/4243b8ac-53fb-4f3a-a1ab-647044e01188)

**Comment by elrrrrrrr** [comment]
@zongzmz 
(⊙o⊙)… 不能直接删除 uk_name，会导致 maintainers 关联关系计算有问题。
什么场景会出现多个同名的用户？
