### ISSUE TITLE
node版本限制问题

### ISSUE THREAD

**Issue by nxps** [cnpm/cnpmcore#530]
cnpmcore项目 node 版本限制是>= 16.13.0，但是 s3-cnpmcore 必须是 18，cnpmcore 的 node 版本限制是否应该升级一下？

**Comment by hezhengxu2018** [comment]
`s3-cnpmcore`是基于aws新版sdk的包装，用到了部分nodejs18的特性。通过配置`CNPMCORE_NFS_TYPE`可以使用别的nfsAdapter，[`s3v2-cnpmcore`](https://github.com/hezhengxu2018/s3v2-cnpmcore)是基于旧sdk的封装，nodejs16也可以运行。当然这部分的配置需要自己添加，不能仅通过环境变量了。
可以修改成推荐nodejs >=18，最低要求依旧是nodejs>=16.13

**Comment by nxps** [comment]
使用 npm 或者 yarn 安装会报错，必须加上参数 --ignore-engines，既然 nodejs16也能运行，s3-cnpmcore 的 node版本限制能改一下吗

**Comment by fengmk2** [comment]
@nxps 报错信息能否发一下，我加一个 optional deps 吧

**Comment by fengmk2** [comment]
![image](https://github.com/cnpm/cnpmcore/assets/156269/d88b3c20-94f3-4572-bc7d-19f61bea4f0e)
看起来只是一个 warning 日志提示？

**Comment by nxps** [comment]
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error s3-cnpmcore@1.1.2: The engine "node" is incompatible with this module. Expected version ">= 18.0.0". Got "16.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by nxps** [comment]
yarn 默认会强制检查

**Comment by fengmk2** [comment]
哦，yarn 是直接报错，我改改
![image](https://github.com/cnpm/cnpmcore/assets/156269/cb7ed178-b8ad-4c8d-802a-ba3d831194f9)

**Comment by fengmk2** [comment]
@nxps 最新的代码分支修复了
