### ISSUE TITLE
【求助】老cnpm升级到cnpmcore以后用户密码重置方案

### ISSUE THREAD

**Issue by shilucus** [cnpm/cnpmcore#538]
升级以后，需要给公司内部用户在新的服务重置密码，目前是手动重置：password_salt+用户提供的密码，重新生成password_integrity并写会数据库。

目前这种方式会有些问题，如果用户不能提供密码（忘记密码），就没办法重置了，只能重新创建个用户，然后再添加相关包的权限。

请问是不是有其他方案可以重置密码？

**Comment by elrrrrrrr** [comment]
npm cli 已经添加了 webAuth 流程的支持。
企业内如果有登录中心的话，更推荐用这种方式来进行授权，这种方式不需要输入账号密码。

https://github.com/cnpm/cnpmcore/blob/master/INTEGRATE.md#-%E9%87%8D%E8%BD%BD-authadapter-%E5%AE%9E%E7%8E%B0
如何是集成模式可以参照这里的文档

如果是直接部署的方式，只需要修改 authAdapter 相关实现即可。😄
