### ISSUE TITLE
npm login与npm addUser报错 

### ISSUE THREAD

**Issue by zongzmz** [cnpm/cnpmcore#540]
![image](https://github.com/cnpm/cnpmcore/assets/6846341/553daf6f-75e1-4790-9be2-c88a996419a3)
回车后 就是下图。。。

![image](https://github.com/cnpm/cnpmcore/assets/6846341/ca6bf99d-9880-4c25-9086-b3d6332e5580)
 config配置文件里面，下图  
![image](https://github.com/cnpm/cnpmcore/assets/6846341/a793f195-5b84-4391-b580-189339441d6f)
因为 npm run start启动后 显示启动的是 127.0.0.1:7001 所以用nginx做的 proxy代理转发到的80端口

我查了下 打包后 就没了login.html页面

**Comment by zongzmz** [comment]
需要复制文件~ 更新下打包配置吧

**Comment by elrrrrrrr** [comment]
@zongzmz 

麻烦补充一下重现方式😯

本地启动的话预期没有 /dist 这个路径

**Comment by zongzmz** [comment]
> @zongzmz
> 
> 麻烦补充一下重现方式😯
> 
> 本地启动的话预期没有 /dist 这个路径

我用的是 3.35.1这个版本 然后 npm run tsc:prod 后 dist目录里面 没有 login.html的页面~ 需要修改打包配置放进去

**Comment by elrrrrrrr** [comment]
@zongzmz 

如果是直接部署方式的话，不需要执行 run build，这个脚本是用来构建 npm 包来二次安装集成的
