### ISSUE TITLE
strictly enforces/validates manifest and tgz

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#542]
https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem?utm_source=ESnextNews.com&utm_medium=Weekly+Newsletter&utm_campaign=2023-07-04

cc @elrrrrrrr

**Comment by elrrrrrrr** [comment]
先完善在当前 registry 上发私有包的场景，公网包还是以 npm registry 为准
