### ISSUE TITLE
[求助]网页改版后,发布 npm 包如何同步到npmmirror.com

### ISSUE THREAD

**Issue by SethLee23** [cnpm/cnpmcore#570]
网页改版后,没有了sync按钮和sync接口,如何同步?

**Comment by fengmk2** [comment]
可以先通过 cnpm cli 的 cnpm sync pkgName 命令同步

**Comment by coader** [comment]
不能手动刷新即时同步 自己发的包就相当于无法立即使用了 非常麻烦

**Comment by coader** [comment]
使用cnpm sync 并没有同步成功 虽然显示成功 但版本未更新

**Comment by fengmk2** [comment]
> 使用cnpm sync 并没有同步成功 虽然显示成功 但版本未更新

发一下日志

**Comment by alienzhangyw** [comment]
别人的包也没法手动同步了。以前npmmirror上同步不及时可以去网页手动点，现在没有了。

**Comment by fengmk2** [comment]
@elrrrrrrr 先搞一下？

**Comment by fengmk2** [comment]
https://npmmirror.com/sync/antd?spm=a2c6h.24755359.0.0.5c8919f1Vuvo95#logid=64d9f4feb0211e50d389362e

先回滚了。

**Comment by coader** [comment]
之前 新版本 除主页外 打开一个具体包的页面要pending 10s左右
