### ISSUE TITLE
切换镜像执行cnpm i报错，node版本14.17.0

### ISSUE THREAD

**Issue by ITAmbition** [cnpm/cnpmcore#579]
PS F:\daasweb\meterfillingh5> npm config set registry https://registry.npmmirror.com
PS F:\daasweb\meterfillingh5> npm get registry
https://registry.npmmirror.com/
PS F:\daasweb\meterfillingh5> cnpm i
× Install fail! TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at resolve (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:53:40)
    at async module.exports (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:25:19)
    at async module.exports (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\index.js:21:10)
    at async _install (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\install.js:124:16)
    at async install (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\install.js:25:12)
    at async installOne (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:208:15)
    at async mapper (D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\local_install.js:147:5)
npminstall version: 6.5.2
npminstall args: F:\nvmtools\nvm\nodejs\node.exe D:\node\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\zhangjiaqi\.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com

**Comment by elrrrrrrr** [comment]
看报错是有依赖没有找到
可能需要提供一下能重现的 package.json 
或者可以在本地打印 D:\node\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js 相关参数排查 🙏🏻

**Comment by ITAmbition** [comment]
{
  "name": "meterfillingh5",
  "title": "抄表h5",
  "version": "1.0.0",
  "remotePath": "/前端产品/工程信息化/meterfillingh5",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@runwork/runwork-help": "^2.4.12",
    "amfe-flexible": "^2.2.1",
    "core-js": "^3.6.5",
    "axios": "^0.20.0",
    "echarts-liquidfill": "^3.0.0",
    "moment": "^2.29.1",
    "vue": "^2.6.14",
    "vue-class-component": "^7.2.6",
    "vue-cookies": "^1.7.4",
    "vue-property-decorator": "^8.4.2",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0",
    "vuex-class": "^0.3.2"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/jest": "^24.0.19",
    "@types/node": "^14.14.6",
    "@typescript-eslint/eslint-plugin": "^2.33.0",
    "@typescript-eslint/parser": "^2.33.0",
    "@vue/cli-plugin-babel": "^4.5.0",
    "@vue/cli-plugin-eslint": "^4.5.0",
    "@vue/cli-plugin-router": "^4.5.0",
    "@vue/cli-plugin-typescript": "^4.5.0",
    "@vue/cli-plugin-unit-jest": "^4.5.0",
    "@vue/cli-plugin-vuex": "^4.5.0",
    "@vue/cli-service": "^4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "@vue/eslint-config-typescript": "^5.0.2",
    "@vue/test-utils": "^1.0.3",
    "babel-plugin-import": "^1.13.1",
    "compressing": "^1.5.1",
    "compression-webpack-plugin": "6.1.1",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^3.0.4",
    "less-loader": "^5.0.0",
    "moment": "^2.29.1",
    "postcss-pxtorem": "^5.1.1",
    "typescript": "~3.9.3",
    "vant": "^2.12.24",
    "vconsole": "^3.7.0",
    "vue-svg-loader": "^0.16.0",
    "vue-template-compiler": "^2.6.11"
  }
}

**Comment by elrrrrrrr** [comment]
@runwork/runwork-help

这个包在公网 unpublish 了

![image](https://github.com/cnpm/cnpmcore/assets/5574625/7e31f413-546d-4033-b434-a7d477b2fa32)

**Comment by ITAmbition** [comment]
OK ,我把这个包删了试试

**Comment by ITAmbition** [comment]
多谢，多谢，解决了
