### ISSUE TITLE
Different tarball with original npm registry.

### ISSUE THREAD

**Issue by JounQin** [cnpm/cnpmcore#588]
https://registry.npmmirror.com/gifsicle/-/gifsicle-5.3.0.tgz

https://registry.npmjs.org/gifsicle/-/gifsicle-5.3.0.tgz

<img width="528" alt="image" src="https://github.com/cnpm/cnpmcore/assets/8336744/8019ffc5-2324-4dc4-b9b6-44722793c40c">

**Comment by yangxiaolang** [comment]
cnpm 有可能用了其他的压缩算法，我手动计算从 `registry.npmjs.org` 和 `registry.npmmirror.com` 两个源的  `gifsicle-5.3.0.tgz`  的 checksum， `registry.npmmirror.com` 的 checksum 似乎对不上
而且我看 `registry.npmmirror.com` 的 `_id` 其实是 `gifsicle@5.2.1`
![企业微信截图_16941616043890](https://github.com/cnpm/cnpmcore/assets/24679861/3dafc9b1-2cf6-41be-9c77-f061a7ea54af)

**Comment by yangxiaolang** [comment]
cnpm 的 `gifsicle@5.3.0` 似乎就是 `gifsicle@5.2.1`，这两个的 checksum 是一致，并且跟 npm 源的 `gifsicle@5.2.1` 的也是一致的

https://www.npmmirror.com/package/gifsicle/files?version=5.3.0#L49
https://www.npmjs.com/package/gifsicle/v/5.3.0?activeTab=code

**Comment by elrrrrrrr** [comment]
@fengmk2 看上去是同步异常了需要手动删除一下异常数据？
`2021-12-13T14:30:33.919Z` 同步时间有点久了，不确定是 npm registry 还是 cnpmcore 的 bug。

**Comment by fengmk2** [comment]
删除命令似乎没有生效

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/package/gifsicle/syncs/6538783382e7e473181113a7/log 已经重新同步

**Comment by fengmk2** [comment]
https://npmmirror.com/package/gifsicle/files?version=5.3.0#L7 缓存已经刷新
