### ISSUE TITLE
请问 npmmirror 和阿里云的关系是？

### ISSUE THREAD

**Issue by ccmywish** [cnpm/cnpmcore#589]
1. npmmirror 属于阿里云吗？还是独立于它？
1.1 如果独立于它，阿里云是提供赞助了吗？
1.2 如果不独立于它，为什么专门搞了一个域名，而不是放在 https://developer.aliyun.com/mirror/ 这里？

3. npmmirror.com 部署在哪里？阿里云吗？

**Comment by fengmk2** [comment]
npmmirror.com 是阿里云赞助的 npm 镜像，在 https://developer.aliyun.com/mirror/NPM 有一个引流。
npmmirror.com 是独立运行的，阿里云赞助了 npmmirror.com 的所有云计算资源，所以是部署在阿里云机房上。

**Comment by ccmywish** [comment]
@fengmk2  感谢感谢，了解了
