### ISSUE TITLE
【扩展请求】请问是否可以将chrome for testing中关于ChromeDriver的内容一并同步下来？

### ISSUE THREAD

**Issue by JokerYF** [cnpm/cnpmcore#591]
ChromeDriver相关团队在114+版本后，就修改了ChromeDriver的发布方式，导致现有阿里源上ChromeDriver只停留到了114版本，是否可以考虑一下，将chrome for testing中关于ChromeDriver的内容一并同步一下？
附相关项目链接
https://googlechromelabs.github.io/chrome-for-testing/
https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=chrome-for-testing/ 不是这个吗？

**Comment by JokerYF** [comment]
> https://registry.npmmirror.com/binary.html?path=chrome-for-testing/ 不是这个吗？

这里只有chrome的包，没有ChromeDriver的包啊

**Comment by fengmk2** [comment]
我也没有经验，https://github.com/cnpm/binary-mirror-config/pull/47 puppeteer 下载 ChromeDriver 的可以参考这个 pr。

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=chrome-for-testing/117.0.5895.0/mac-arm64/ 已经有了。
