### ISSUE TITLE
【扩展请求】是否有计划将edgedriver列入同步列表中？

### ISSUE THREAD

**Issue by JokerYF** [cnpm/cnpmcore#594]
RT
是否可以将edge浏览器驱动更新到源中？并将latest release文件一并同步？
附：
edgedriver驱动官网：https://developer.microsoft.com/zh-cn/microsoft-edge/tools/webdriver/
edgedriver latest release url：https://msedgedriver.azureedge.net/LATEST_RELEASE_117_MACOS

**Comment by fengmk2** [comment]
这是被用在那个 npm 包的？

**Comment by elrrrrrrr** [comment]
ping @JokerYF 😄

**Comment by mindfocus** [comment]
selenium 4吧 大概

**Comment by fengmk2** [comment]
> selenium 4吧 大概

能否提供一个使用方式？触发一下 selenium 下载 edgedriver 的逻辑

**Comment by fengmk2** [comment]
https://github.com/webdriverio-community/node-edgedriver 这个？

**Comment by fengmk2** [comment]
https://github.com/webdriverio-community/node-edgedriver/commit/84b331f7b431ee8997ae9ee74d2d84b0f4fd7ec2 支持环境变量。

**Comment by fengmk2** [comment]
通过 https://edgeupdates.microsoft.com/api/products 读取到 edge 的 release 版本，然后 https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver?prefix=124.0.2478.97%2F&delimiter=%2F&maxresults=100&restype=container&comp=list 可以获取到下载地址

https://msedgewebdriverstorage.z22.web.core.windows.net/?prefix=126.0.2566.1/ 这里是一个 web 界面

**Comment by fengmk2** [comment]
已经发布，等待同步 https://r.cnpmjs.org/binary.html?path=edgedriver/

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/binary.html?path=edgedriver/ 中国镜像

**Comment by fengmk2** [comment]
```bash
EDGEDRIVER_CDNURL=https://npmmirror.com/mirrors/edgedriver EDGEDRIVER_VERSION=126.0.2578.0 npx edgedriver -v    
Microsoft Edge WebDriver 126.0.2578.0 (cb8ca64d8bf9848cd95851ce8397d01f7f4c69b2)
```
