### ISSUE TITLE
请问登录npm源，可以使用类似_authToken方式嵌入CI流程登录吗？

### ISSUE THREAD

**Issue by yang200258** [cnpm/cnpmcore#611]
请问登录npm源，可以使用类似_authToken方式嵌入CI流程登录吗？

**Comment by yang200258** [comment]
用`echo -e "usename\npassword\n" | npm login --auth-type=legacy`

会报错：
![image](https://github.com/cnpm/cnpmcore/assets/38518538/0596f021-266d-4d70-9e71-02085d10a904)

**Comment by elrrrrrrr** [comment]
@yang200258 

issue 我先 close 啦，如果还要继续沟通可以随时 reopen 🙏🏻
