### ISSUE TITLE
CDN 支持 brotli 压缩算法

### ISSUE THREAD

**Issue by faceair** [cnpm/cnpmcore#617]
客户端现在一般同时支持 brotli、gzip 压缩方式，但 brotli 压缩率会略高于 gzip，推荐在 CDN 的配置中开启优先使用 brotli 压缩的选项。

实测在请求 CDN 地址时 https://registry.npmmirror.com/amis/3.6.1/files/sdk/sdk.css 后端默认选择了 gzip。

<img width="512" alt="image" src="https://github.com/cnpm/cnpmcore/assets/3659110/b87bfd7b-a71a-4441-a80f-5ac705702a7c">

<img width="512" alt="image" src="https://github.com/cnpm/cnpmcore/assets/3659110/9f8a192a-5422-40b5-9323-feb5acfa9561">

**Comment by fengmk2** [comment]
得看看阿里云 cdn 是否支持配置优先 brotli

**Comment by fengmk2** [comment]
现在改不了，我们源站是经过了 nginx gzip 压缩再返回给 cdn，cdn 只会原样转发。

**Comment by faceair** [comment]
源站 nginx 也可以配置支持 brotli 吧
