### ISSUE TITLE
周开始日期计算逻辑似乎有缺陷，dayjs默认返回周日作为周的第一天

### ISSUE THREAD

**Issue by baxtergu** [cnpm/cnpmcore#618]
HomeController 中的 downloads week 计算逻辑可能有影响。

```js
// 2023-12-05
dayjs().startOf('week').  2023-12-03 00:00:00
dayjs().startOf('isoWeek').  2023-12-04 00:00:00

```

https://github.com/iamkun/dayjs/issues/2283

计算周下载量的时候从周日开始算了

**Comment by hezhengxu2018** [comment]
对基督徒来说一周的开始是周日，统计这个更多的意义是对数据量感性的认知，只要是完整的7天作为一个周期即可。一周的开始究竟应该是周日还是周一差别不大。我觉得在某次相关的mr里顺便改了是合理的，就这样保持现状也没问题。

**Comment by baxtergu** [comment]
close
