### ISSUE TITLE
cacheKeyNormalize 存在性能问题

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#624]
![image](https://github.com/cnpm/cnpmcore/assets/156269/50736de0-4295-4e96-9144-f3cb6962cff3)

node_modules/_tar@6.2.0@tar/lib/unpack.js
node_modules/_tar@6.2.0@tar/lib/normalize-unicode.js

长期方案
- [ ] 使用 compressing 或者 tar-stream 代替

**Comment by fengmk2** [comment]
https://github.com/isaacs/node-tar/blob/5bc9d404e88c39870e0fbb55655a53de6fbf0a04/lib/unpack.js#L108

**Comment by fengmk2** [comment]
https://github.com/isaacs/node-tar/blob/5bc9d404e88c39870e0fbb55655a53de6fbf0a04/lib/normalize-unicode.js#L9 
![image](https://github.com/cnpm/cnpmcore/assets/156269/63027c7a-5916-4ab1-b97a-c0d42acbd9bc)
存在内存泄漏？

**Comment by fengmk2** [comment]
normalizeCache 的 key 每次 tar unpack 之后都会递增。
![image](https://github.com/cnpm/cnpmcore/assets/156269/7bc8c82b-f1c6-420d-9330-2a214be10108)

**Comment by fengmk2** [comment]
https://github.com/isaacs/node-tar/pull/286/files#r1429388455

**Comment by fengmk2** [comment]
https://github.com/node-modules/compressing/blob/master/package.json#L48C6-L48C16 呃，难怪以前没有出现过这个问题

**Comment by fengmk2** [comment]
ezm headdump 也抓到了
![image](https://github.com/cnpm/cnpmcore/assets/156269/be459d23-68e9-4f92-bcc7-4623a22e1b06)

**Comment by barretlee** [comment]
从内网之前的分析来看，堆内内存占用并不大，主要是堆外占用很大，而堆外大部分都是碎片内存。

也就是说，在 unpack 之后，在 `normalizeCache` 对象储存了大量的 key-value 对，但是由于存在少量 key/value 仍然被后续的程序使用（猜测）导致整个 normalizeCache 对象都没有被释放。

经历了多次 unpack 后，堆外内存就暴涨了。因此泄露的不是 heap。

**Comment by fengmk2** [comment]
> 从内网之前的分析来看，堆内内存占用并不大，主要是堆外占用很大，而堆外大部分都是碎片内存。
> 
> 也就是说，在 unpack 之后，在 `normalizeCache` 对象储存了大量的 key-value 对，但是由于存在少量 key/value 仍然被后续的程序使用（猜测）导致整个 normalizeCache 对象都没有被释放，这里说的没释放是没有释放给系统，被 ptmalloc 的 main arena 给保留了，原因是 top chunk 附近存在未回收内存。
> 
> 经历了多次 unpack 后，堆外内存就暴涨了。因此泄露的不是 heap。

这个不是的，这个是真的 heap 泄漏，js 代码实现问题。

**Comment by barretlee** [comment]
> 这个不是的，这个是真的 heap 泄漏，js 代码实现问题。

那就是存在不止一个问题咯

**Comment by fengmk2** [comment]
RSS 内存泄漏 https://zhuanlan.zhihu.com/p/675317993
