### ISSUE TITLE
[需求]：Ant Design Charts 官网产物同步

### ISSUE THREAD

**Issue by lxfu1** [cnpm/cnpmcore#635]
1. 同步[Ant Design Charts](https://github.com/ant-design/ant-design-charts/releases) Site 产物

**Comment by Beace** [comment]
我看产物不就是包吗，需要同步什么

**Comment by fengmk2** [comment]
@lxfu1 你将 https://github.com/ant-design/ant-design-charts/blob/v2/site/package.json 发布到 npm 是否就可以了？我看看 ant-design-charts-Site_2.1.11.zip 也就 6MB

**Comment by elrrrrrrr** [comment]
😄 @MadCcc @zombieJ 

看看 antd site 是不是也一起搞个 tgz 托管方案

**Comment by fengmk2** [comment]
@lxfu1 好了 https://registry.npmmirror.com/binary.html?path=ant-design-charts/Site_2.1.11/
