### ISSUE TITLE
[optimize] npm binary URL config guide or auto-redirect correct

### ISSUE THREAD

**Issue by genffy** [cnpm/cnpmcore#649]
recently([2024-01-22 10:26:01](https://twitter.com/fengmk2/status/1749276617187221906)) the `npm.taobao.org` totaly unuseful, and many `x_cdnurl`, `x_binary_site`, `x_mirror` got error response.

But there is no a complete guide to how to change it properly, and some old URL redirects are not correct.

```
# old
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

# temp used
# will redirect to https://cdn.npmmirror.com/binaries/node-sass
sass_binary_site=https://npmmirror.com/mirrors/node-sass

# correct
sass_binary_site=https://registry.npmmirror.com/-/binary/node-sass
```

**Comment by fengmk2** [comment]
https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L49 参考这里的环境变量配置。

**Comment by genffy** [comment]
> https://github.com/cnpm/binary-mirror-config/blob/master/package.json#L49 参考这里的环境变量配置。

这里的配置实际上是不太对的，比如 
<img width="689" alt="Screenshot 2024-02-25 at 17 23 56" src="https://github.com/cnpm/cnpmcore/assets/1506972/8a2cda5f-3b42-4ddd-8b72-13e0eb16f2d6">
点了几个测试，不知道是不是我用的方法不对
