### ISSUE TITLE
@gamex/cc-sap无法同步

### ISSUE THREAD

**Issue by a1076559139** [cnpm/cnpmcore#663]
https://npmmirror.com/package/@gamex/cc-sap
似乎遇到了什么BUG，无法安装，也无法同步

**Comment by a1076559139** [comment]
今天凌晨3点左右我提交第一个版本到npm上，然后间隔了有1分钟吧，我通过`npm npm --registry=https://registry.npmmirror.com install @game/cc-sap`的方式尝试安装了几次都没成功，然后就睡觉了，现在发现它貌似进入了某个Bug状态

**Comment by fengmk2** [comment]
好了，可以通过 cnpm sync @gamex/cc-sap 进行通过
