### ISSUE TITLE
请问，部署完成后怎么进行包同步呢

### ISSUE THREAD

**Issue by aimeiyijia** [cnpm/cnpmcore#664]
感谢

**Comment by aimeiyijia** [comment]
如何全量同步npm呢

**Comment by hezhengxu2018** [comment]
syncMode设成all就会进行全量同步

**Comment by aimeiyijia** [comment]
> syncMode设成all就会进行全量同步

<img width="509" alt="image" src="https://github.com/cnpm/cnpmcore/assets/43396646/90f08482-ea90-407f-ae17-d9368be71a40">
我设置成了all，但是没发现有同步，

**Comment by hezhengxu2018** [comment]
定时任务每5分钟会从`https://www.npmjs.com/browse/updated`，https://github.com/cnpm/cnpmcore/blob/ebc212c1c4f0f45b54951c19c3ca785e2c6b32f9/app/port/schedule/CheckRecentlyUpdatedPackages.ts#L32
可以打断点看一下是不是创建同步任务的时候出了问题

**Comment by aimeiyijia** [comment]
> 定时任务每5分钟会从`https://www.npmjs.com/browse/updated`获取最近同步的包创建更新任务。
> 
> https://github.com/cnpm/cnpmcore/blob/ebc212c1c4f0f45b54951c19c3ca785e2c6b32f9/app/port/schedule/CheckRecentlyUpdatedPackages.ts#L32
> 
> 
> 可以打断点看一下是不是创建同步任务的时候出了问题

我是用cnpmcore npm包搭的

**Comment by aimeiyijia** [comment]
> 定时任务每5分钟会从`https://www.npmjs.com/browse/updated`获取最近同步的包创建更新任务。
> 
> https://github.com/cnpm/cnpmcore/blob/ebc212c1c4f0f45b54951c19c3ca785e2c6b32f9/app/port/schedule/CheckRecentlyUpdatedPackages.ts#L32
> 
> 
> 可以打断点看一下是不是创建同步任务的时候出了问题

hello tegg那个项目，自己发布的包能在存储器上看到，但是没全量同步npm

**Comment by aimeiyijia** [comment]
> The scheduled task will obtain the recently synchronized package creation and update task from `https://www.npmjs.com/browse/updated` every 5 minutes.
>
> https://github.com/cnpm/cnpmcore/blob/ebc212c1c4f0f45b54951c19c3ca785e2c6b32f9/app/port/schedule/CheckRecentlyUpdatedPackages.ts#L32
>
>
> You can break the point to see if there is a problem when creating the synchronization task.

CheckRecentlyUpdatedPackages.subscribe:error][1] request https://www.npmjs.com/browse/updated?offset=36 error: HttpClientConnectTimeoutError: Connect Timeout Error    连接超时 不知道为什么

**Comment by elrrrrrrr** [comment]
全量包同步目前分为几个步骤。

1. 存量部分: 通过脚本来触发同步任务，脚本可以参考：[ref](https://github.com/cnpm/cnpmcore/blob/sync-all-packages/test/SyncAllPackages.ts)。
3. 增量部分: 通过管理员账号，调用 `POST` `/-/registry/:registryId/sync` 初始化 changesStream 同步任务，接口将实时订阅上游 registry 相关变更。

**Comment by elrrrrrrr** [comment]
> 定时任务每5分钟会从`https://www.npmjs.com/browse/updated`获取最近同步的包创建更新任务。

这个是辅助同步，防止 npm 官方的 registry changesStream 不太稳定。

**Comment by elrrrrrrr** [comment]
@aimeiyijia 目前还缺一个比较细致的启动文档，方便的话可以一起补充下需求背景及目前的 registry、users 相关配置和 db 内数据

**Comment by aimeiyijia** [comment]
> 2\. registryId

不太明白，registryId从哪里来的

**Comment by aimeiyijia** [comment]
> @aimeiyijia 目前还缺一个比较细致的启动文档，方便的话可以一起补充下需求背景及目前的 registry、users 相关配置和 db 内数据

主要需求是在内网部署一个仓库，然后定期到外网同步f

**Comment by aimeiyijia** [comment]
> 2\. /-/registry/:registryId/sync
第二部理解不了

**Comment by elrrrrrrr** [comment]
@aimeiyijia 

我添加了一个启动文档，看看是否能解决你遇到的问题。

过程中如果遇到其他问题，可以一起反馈 🙏🏻 我将尽量补充到文档中。

**Comment by aimeiyijia** [comment]
> @aimeiyijia
> 
> 我添加了一个启动文档，看看是否能解决你遇到的问题。
> 
> 过程中如果遇到其他问题，可以一起反馈 🙏🏻 我将尽量补充到文档中。
谢谢，我试着操作一下

**Comment by aimeiyijia** [comment]
> CheckRecentlyUpdatedPackages.subscribe:error][1] request https://www.npmjs.com/browse/updated?offset=36 error: HttpClientConnectTimeoutError: Connect Timeout Error  还是一直报错，history_tasks表里全是fail

**Comment by aimeiyijia** [comment]
@elrrrrrrr

**Comment by elrrrrrrr** [comment]
@aimeiyijia 直接用 cnpm 源同步？ 

https://github.com/cnpm/cnpmcore/blob/docs-sync/docs/sync-setup.md#-%E4%BD%BF%E7%94%A8-cnpm-%E4%BD%9C%E4%B8%BA%E9%BB%98%E8%AE%A4%E7%9A%84%E5%90%8C%E6%AD%A5%E6%BA%90

这个报错应该是网络问题，试试 `curl -vvv 'https://www.npmjs.com/browse/updated?offset=36'` 能访问吗？

**Comment by aimeiyijia** [comment]
> @aimeiyijia 直接用 cnpm 源同步？
> 
> https://github.com/cnpm/cnpmcore/blob/docs-sync/docs/sync-setup.md#-%E4%BD%BF%E7%94%A8-cnpm-%E4%BD%9C%E4%B8%BA%E9%BB%98%E8%AE%A4%E7%9A%84%E5%90%8C%E6%AD%A5%E6%BA%90
> 
> 这个报错应该是网络问题，试试 `curl -vvv 'https://www.npmjs.com/browse/updated?offset=36'` 能访问吗？

不能访问，但是不知道为啥，换了几个电脑，网络环境也换了

**Comment by aimeiyijia** [comment]
> @aimeiyijia 直接用 cnpm 源同步？
> 
> https://github.com/cnpm/cnpmcore/blob/docs-sync/docs/sync-setup.md#-%E4%BD%BF%E7%94%A8-cnpm-%E4%BD%9C%E4%B8%BA%E9%BB%98%E8%AE%A4%E7%9A%84%E5%90%8C%E6%AD%A5%E6%BA%90
> 
> 这个报错应该是网络问题，试试 `curl -vvv 'https://www.npmjs.com/browse/updated?offset=36'` 能访问吗？

这个地址有npmmirror替换地址吗

**Comment by aimeiyijia** [comment]
> @aimeiyijia 直接用 cnpm 源同步？
> 
> https://github.com/cnpm/cnpmcore/blob/docs-sync/docs/sync-setup.md#-%E4%BD%BF%E7%94%A8-cnpm-%E4%BD%9C%E4%B8%BA%E9%BB%98%E8%AE%A4%E7%9A%84%E5%90%8C%E6%AD%A5%E6%BA%90
> 
> 这个报错应该是网络问题，试试 `curl -vvv 'https://www.npmjs.com/browse/updated?offset=36'` 能访问吗？

请问下 你知道全量同步，需要准备多大的存储空间吗

**Comment by aimeiyijia** [comment]
> > @aimeiyijia 直接用 cnpm 源同步？
> > https://github.com/cnpm/cnpmcore/blob/docs-sync/docs/sync-setup.md#-%E4%BD%BF%E7%94%A8-cnpm-%E4%BD%9C%E4%B8%BA%E9%BB%98%E8%AE%A4%E7%9A%84%E5%90%8C%E6%AD%A5%E6%BA%90
> > 这个报错应该是网络问题，试试 `curl -vvv 'https://www.npmjs.com/browse/updated?offset=36'` 能访问吗？
> 
> 请问下 你知道全量同步，需要准备多大的存储空间吗

@elrrrrrrr

**Comment by fengmk2** [comment]
全量需要几十 TB

**Comment by elrrrrrrr** [comment]
> 这个地址有npmmirror替换地址吗

没有的，这个是用来辅助更新的，后续我加个配置允许关闭
