### ISSUE TITLE
✨[Feature request] Support for unpkg-like auto-redirection capabilities

### ISSUE THREAD

**Issue by chilingling** [cnpm/cnpmcore#674]
【特性描述】

支持类似 unpkg 的自动重定向能力。
如： 

https://unpkg.com/@opentiny/vue-theme@~3.11/theme-tool ->  https://unpkg.com/@opentiny/vue-theme@3.11.6/theme-tool.js
https://unpkg.com/@opentiny/vue-theme@~3.11/theme -> https://unpkg.com/@opentiny/vue-theme@3.11.6/theme/index.js

【使用场景】

在 import map 相关的场景中使用。比如：

importmap：

```json
{
  "@opentiny/vue-theme/theme-tool": "https://unpkg.com/@opentiny/vue-theme@~3.11/theme-tool",
    "@opentiny/vue-theme/theme": "https://unpkg.com/@opentiny/vue-theme@~3.11/theme"
}
```

使用：

```javascript
import TinyThemeTool from '@opentiny/vue-theme/theme-tool' // 会自动请求 https://unpkg.com/@opentiny/vue-theme@~3.11/theme-tool ，然后重定向到 https://unpkg.com/@opentiny/vue-theme@3.11.6/theme-tool.js
import { tinySmbTheme } from '@opentiny/vue-theme/theme'
```

即支持 MDN 中 import map 提到的[路径前缀](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/script/type/importmap#%E6%98%A0%E5%B0%84%E8%B7%AF%E5%BE%84%E5%89%8D%E7%BC%80) 并自动重定向能力。

![image](https://github.com/cnpm/cnpmcore/assets/26962197/95e818b0-9871-45dd-953b-01a04056bfdb)

感谢 ❤

**Comment by atian25** [comment]
```bash
$ curl https://registry.npmmirror.com/@opentiny/vue-theme/\~3.11/files/theme-tool.js
Redirecting to <a href="/@opentiny/vue-theme/3.11.6/files/theme-tool.js">/@opentiny/vue-theme/3.11.6/files/theme-tool.js</a>.%   
```

看起来是支持的

**Comment by chilingling** [comment]
> ```shell
> $ curl https://registry.npmmirror.com/@opentiny/vue-theme/~3.11/files/theme-tool.js
> Redirecting to <a href="/@opentiny/vue-theme/3.11.6/files/theme-tool.js">/@opentiny/vue-theme/3.11.6/files/theme-tool.js</a>.%   
> ```
> 
> 看起来是支持的

是请求 https://registry.npmmirror.com/@opentiny/vue-theme/~3.11/files/theme-tool 的时候，重定向到 https://registry.npmmirror.com/@opentiny/vue-theme/~3.11/files/theme-tool.js

**Comment by atian25** [comment]
importmap 是配置在前端，由浏览器来支持的吧？

**Comment by chilingling** [comment]
我做了个简单的 [复现demo](https://play.vuejs.org/#eNqtVM1uEzEQfhWzHApSdt2orUBpWkGrHkAIKprjXjabSeJ2/SPbm6ZEuYGEBFcQFy5IiDdASOVxGiHegrF381e2UVv1srI938/MeD2j4KlS0SCHoBE0TaqZssSAzdVuLCglk9+fJu++kydSgbBMnFFEkj/nby/Of8aCcSW1JSOyL0WX9Q61HLAOaJIY0kLs8mmN7OXWSjGNFrsaecHEyfTMr8ekqyUna0ueazO3DhjWE0e8XchXgcMCExrenvOcfqsPHFpSZpUs66LUf0OLoDl3RBwIPb1AdYaLdGTGQsDpsumDRZEaWcP0CvRD4jr9/uvkx4fJx88Xv87/fvviFFIpjCXc9MgOWetDlklyKnXWuef1m7S4rl1CiN9b4CpLLODNEdJ0ZiEqYI9CNb2ZRtGZnTi41MY48CzkddigXOKmX98djXwG43GT4q4E0SmqSat8MISBeTq4NfYsA2JSbFnHM/v1USGWykzqxv0teJTC+jaWQsjYfSKnjI0tYV0pbGjYG2iQ+uOh2v4PF6qkB6RStMRix1wWaB/UguJqQ56o6NhIgb+/p8ZlwMRBYyoWB0s37SJx0LdWmQalGnrMWH0WCcU501rqKJWcLjHoRlTfpF2WgaE6x2P3o7i+YSzix+hVq3QKGTb2bu285ErPTKZJdsdFlqIrfVGQ33m1hehK3+Ld3ty3JC64r7YIuWwj7NZOU/51DDUIfIYIcZgb2y2wq80MPpCknYHr6jXU53Baj+pb0XqpyGUnzxI9i0dgOD7GK6uaj/VbFDUnLxbFsNKh9yxnxBhHg8Ux5ebZpcGAmgpJ+pWyDCfz0oBIcDifPvdnVucwKyDtQ3pScX5shkUNhxoM6AG+t1nMJroHtggfHL2EIa5nQd+z8nVeEXwNRma5y7GA7eWig2kv4Hy2z/ycY6LXMgdDC8JMi3KJ+m54fBxg9/ZXlD5PdyPanHVx/A+7GO8Q)
在 demo 可以发现，theme-tool 和 theme 的两个请求挂了。
unpkg 的 [对比demo](https://play.vuejs.org/#eNqlVM1u00AQfpXBHAJSbDdqK1CaRqVVDyAEFc3RF8fZOm69P9pdpylRbiAhwRXEhQsS4g0QUnmcRoi3YHbXiZvWDUW9WN6Zb7759tudnXhPhAhGBfHaXkclMhMaFNGF6EYsDGH26+Ps7TfY4YIwnbGzEJHw+/zNxfmPiGVUcKlhAnucHWXpgeSjbEAkxAp6iF2ONmG30JqzedatmvA8YyfzmP2fwpHkFBpLPRuLbgOispQd0r6jrwP7DuMr2q/qDH9vSCjpcZ7XVmmTDe3X1wiqaidgQNjTEtQrvFyOlRFj5HS56YPLJE1ooDyHfgjG6XdfZt/fzz58uvh5/ufrZ8OQcKY0UJXCNjSGJM85nHKZD+5Z/k7ojqsLAHatCRV5rAmeHEDHNPORAT3yxfxk2s6Z7ci7YmPk2SqsG2SjbmfY6k4mtvN02glx1QlN3BKHdcyYwkQlAJdKn+UEVIImDWzlsDVxPRKec9m+v0keJWRtC8UDTM0nMMxoZQk74kz7KntN2tB6PBZb13C+iFMCtaQlFj0yKrC91/TcYfo0FsGx4gwvvC2NyoSKvPacLPKWztZkIm+otVDtMCyYOEmDhNNwCbSzHrQ2QllgwNwDYxJGA3qMxM1aWj9DF+/AbetXNsh5Eud3kV8yrGyCVPRu+3AMK5u46bpVE4d1rVbz+ZT3s/y/aMuSf7BLwnAocqLULbmrgmvMCu9m3M+JMaeeqkLstILWZrAWUj4o8lguMgFRFC/9jXqrB/N2ciu8k5uh+rFtUA7eFOdN4+ybR+LKtCGbQAflS6EzfOCWpi7GN+70mY1pWZCF2mRIkpOa+LEaO8EHkigiR3jVFzkdy5Rol94/fEHG+L9IWoPKwbgh+YoonhdGo4PtFmyAsi/hrNqn9vHIWNpT+2NNmJpvygi1blh85KFveyu2XsldDzYWLk7/Agysp9s=) ，请求正常，渲染成功

**Comment by atian25** [comment]
![image](https://github.com/cnpm/cnpmcore/assets/227713/ceeaf073-c96c-4375-b065-a48616f8ce25)
![image](https://github.com/cnpm/cnpmcore/assets/227713/c8dec547-deef-42db-86bf-111b068b481d)

看了下，应该不是 importmap，这是在浏览器侧就支持转换了，更像是后缀名的自动补齐：

https://unpkg.com/@opentiny/vue-theme@3.14.1/theme-tool → https://unpkg.com/@opentiny/vue-theme@3.14.1/theme-tool.js

**Comment by atian25** [comment]
去看下 unpkg 的文档是不是有类似的约定？

**Comment by chilingling** [comment]
unpkg 具体实现的逻辑应该是这一块：https://github.com/mjackson/unpkg/blob/af8c8db00fdacd77961ab2a8c3edb45a27d3a6a3/modules/middleware/findEntry.js#L176-L190

**Comment by chilingling** [comment]
没理解错的话，cnpmcore 应该在这个[函数](https://github.com/cnpm/cnpmcore/blob/master/app/port/controller/PackageVersionFileController.ts#L183-L210)内尝试增加规则匹配：

- /dir/index  -> 全匹配失败的话，尝试匹配  /dir/index.js 、/dir/index.json
- /dir/fileName  -> 全匹配失败的话，尝试匹配 /dir/fileName.js

然后在[这附近](https://github.com/cnpm/cnpmcore/blob/master/app/port/controller/PackageVersionFileController.ts#L147-L161) 查看查找到的文件与当前 path 是否一致，如果不一致，则302到匹配的路径

**Comment by atian25** [comment]
@chilingling 直接来 PR 吧～

**Comment by chilingling** [comment]
> @chilingling 直接来 PR 吧～

我试试

**Comment by fengmk2** [comment]
@chilingling 感谢开源贡献！已经成功

![image](https://github.com/cnpm/cnpmcore/assets/156269/d8ca6341-b3b5-42ce-9c59-b4732a452125)
