### ISSUE TITLE
files 需要增加文件后缀白名单

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#693]
允许的白名单后缀：
- `.js`, `.ts`, `.jsx`, `.tsx`, `.cjs`, `.mjs`
- `.css`, `.less`, `.sass`
- `.json`, `.json5`
- `.yml`, `.yaml`, `.toml`, `.xml`
- `.axml`, `.sjs`
- `.wxml`
- `.woff`, `.woff2`, `.eot`, `.ttf`, `.otf`
- `.wasm`
- `.md`, `.markdown`
- `.sql`
- `.puml`

文件名白名单：
- `README`
- `LICENSE`, `LICENSE.txt`
- `AUTHORS`
- `configure`, `Makefile`
- `Dockerfile`, `.dockerignore`
- `.gitignore`
- `.eslintrc`, `.eslintignore`
- `.npmrc`

**Comment by fengmk2** [comment]
https://github.com/jshttp/mime-db/blob/master/src/nginx-types.json

**Comment by ChangedenCZD** [comment]
配置文件后缀 `yaml`、`toml`

**Comment by BlackHole1** [comment]
XML

> BTW，只检测后缀无法避免滥用情况，如: `m3u8` 中的视频分段使用的是 `ts` 文件，这会与白名单中的 `.ts` 吻合。
> 或许还需要增加: `File Magic Numbers` 的判断 以及 最大文件大小的判断

**Comment by fengmk2** [comment]
> XML
> 
> > BTW，只检测后缀无法避免滥用情况，如: `m3u8` 中的视频分段使用的是 `ts` 文件，这会与白名单中的 `.ts` 吻合。
> > 或许还需要增加: `File Magic Numbers` 的判断 以及 最大文件大小的判断

File Magic Numbers 我对 ts 加一下判断

**Comment by i18n-now** [comment]
我感觉小于256KB的文件就别判断了，我有些二进制的语言文件用的.js后缀，还是从流量异常上监控比较好

**Comment by FloatSheep** [comment]
网页后缀 `html`

**Comment by fjc0k** [comment]
@fengmk2 哥，我觉得这个功能最好关了好，安全第一，黑产灰产都是其次，涉政才是要命的。要做也建议就同步cdnjs，它有哪些包，咱就只支持哪些包。
v2ex看到这个帖子：https://www.v2ex.com/t/1047740
![image](https://github.com/cnpm/cnpmcore/assets/13151189/72226f89-d2b2-4217-9454-45f28127f6c2)
![image](https://github.com/cnpm/cnpmcore/assets/13151189/9add9062-466d-451e-af42-599f94202f97)

**Comment by fengmk2** [comment]
@fjc0k 这个没有准确消息吧

**Comment by fjc0k** [comment]
@fengmk2 只是觉得很难把内容审查做好，让上面满意，毕竟这玩意儿没有具体标准。与其留下个炸弹可能波及镜像服务被关闭，还不如提前预防。

**Comment by lisonge** [comment]
发现个漏洞，允许 `xml` 相当于允许 `html`

测试 <https://registry.npmmirror.com/@gkd-kit/inspect/0.0.1749439290229/files/dist/test.xml>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0,user-scalable=no,minimal-ui"/>
        <style type="text/css">
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
            iframe {
                display: block;
                width: 100%;
                height: 100%;
                border: none;
            }
        </style>
    </head>
    <body>
        <h1>test xml</h1>
        <h1> <a href="https://v2ex.com/t/1137419">https://v2ex.com/t/1137419</a> </h1>
    </body>
</html>
```

相关讨论 <https://v2ex.com/t/1137419>

---

可以通过将 `xml` 文件的 `content-type` 设置为 `text/plain` 避免此类问题

**Comment by elrrrrrrr** [comment]
> 发现个漏洞，允许 `xml` 相当于允许 `html`
> 
> 测试 https://registry.npmmirror.com/@gkd-kit/inspect/0.0.1749439290229/files/dist/test.xml
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
>     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> <html xmlns="http://www.w3.org/1999/xhtml">
>     <head>
>         <title></title>
> 		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0,user-scalable=no,minimal-ui"/>
>         <style type="text/css">
>             html, body {
>                 height: 100%;
>                 margin: 0;
>                 padding: 0;
>             }
>             iframe {
>                 display: block;
>                 width: 100%;
>                 height: 100%;
>                 border: none;
>             }
>         </style>
>     </head>
>     <body>
>         <h1>test xml</h1>
>         <h1> <a href="https://v2ex.com/t/1137419">https://v2ex.com/t/1137419</a> </h1>
>     </body>
> </html>
> 相关讨论 https://v2ex.com/t/1137419
> 
> 可以通过将 `xml` 文件的 `content-type` 设置为 `text/plain` 避免此类问题

感谢反馈 🙏🏻 我们尽快处理下

**Comment by elrrrrrrr** [comment]
![Image](https://github.com/user-attachments/assets/db96b2a1-2768-4a6f-bcda-b0710ad09367)

线上 content-type 规则生效，再次感谢 @lisonge  ❤️
