### ISSUE TITLE
perf: diff

### ISSUE THREAD

**Issue by fengmk2** [cnpm/cnpmcore#698]
application/app/core/service/BinarySyncerService.js:221
![image](https://github.com/cnpm/cnpmcore/assets/156269/847703f3-99e9-4fb4-a495-1e7b32ab6f0e)

**Comment by fengmk2** [comment]
https://github.com/cnpm/cnpmcore/blob/master/app/core/service/BinarySyncerService.ts#L279
![image](https://github.com/cnpm/cnpmcore/assets/156269/845997ea-672c-48c5-82b7-2df044e4c552)

**Comment by elrrrrrrr** [comment]
https://github.com/cnpm/cnpmcore/pull/647#discussion_r1517181778

我梦到过这段
