### ISSUE TITLE
下载不到老版本的npm

### ISSUE THREAD

**Issue by RiESAEX** [cnpm/cnpmcore#703]
在sourceRegistry配成https://registry.npmmirror.com的时候
用nvm-windows下载node14.会下载不到npm
抓包看nvm-windows的请求 在装node14的时候最后会去请求/-/binary/npm/v6.14.15.zip
然后响应了一个`{"error":"[NOT_FOUND] Binary \"npm/v6.14.15.zip\" not found"}`回来

**Comment by elrrrrrrr** [comment]
https://registry.npmmirror.com/binary.html?path=npm/v6.14.15/

https://registry.npmmirror.com/-/binary/npm/v6.14.15/v6.14.15.zip

看着有这个文件

**Comment by RiESAEX** [comment]
https://registry.npmmirror.com/-/binary/npm/v6.14.15/v6.14.15.zip 有文件但是https://registry.npmmirror.com/-/binary/npm/v6.14.15.zip 会直接NOT_FOUND回来
走https://npmmirror.com/mirrors/npm/ 的话就会有两次302 
https://npmmirror.com/mirrors/npm/v6.14.18.zip -> https://cdn.npmmirror.com/binaries/npm/v6.14.18.zip -> https://cdn.npmmirror.com/binaries/npm/v6.14.18/v6.14.18.zip

**Comment by elrrrrrrr** [comment]
![image](https://github.com/user-attachments/assets/7dd8132a-8644-415e-bc61-5aa418a187d3)

手上没有 windows 机器，在 linux 下没有重现 🤔

**Comment by RiESAEX** [comment]
是的 好像只有nvm-windows会单独走一个请求去下npm，nvm和fnm看起来都是直接用node的tar包里面带的npm。

**Comment by fengmk2** [comment]
这是 npm-windows 的问题
