### ISSUE TITLE
skia-canvas 二进制地址已修改导致没有同步

### ISSUE THREAD

**Issue by ltxhhz** [cnpm/cnpmcore#710]
在 [skia-canvas](https://www.npmjs.com/package/skia-canvas) 最新的 `1.0.2` 版本中，二进制地址被修改了，似乎导致 [npmmirror binary](https://registry.npmmirror.com/binary.html?path=skia-canvas/) 没同步成
https://github.com/samizdatco/skia-canvas/blob/962f21bd35f06e9477b57cb2a2c1d05a16d35f1a/package.json#L52

直接修改这里的 `distUrl` 和 `options` 会生效吗
https://github.com/cnpm/cnpmcore/blob/e6ed2215a4b1d91ec555e8f7a4ee6d3e4378a2cc/config/binaries.ts#L134-L142

**Comment by elrrrrrrr** [comment]
@ltxhhz 直接提个 pr 😄？

**Comment by fengmk2** [comment]
已经成功 https://registry.npmmirror.com/binary.html?path=skia-canvas/

```bash
[1/1] scripts.install skia-canvas@latest run "node-pre-gyp install || npm run build -- --release", root: "/Users/fengmk2/git/github.com/cnpm/cnpmcore/node_modules/_skia-canvas@1.0.2@skia-canvas"
(node:28817) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp http GET https://cdn.npmmirror.com/binaries/skia-canvas/v1.0.2/darwin-arm64-unknown.tar.gz
[skia-canvas] Success: "/Users/fengmk2/git/github.com/cnpm/cnpmcore/node_modules/_skia-canvas@1.0.2@skia-canvas/lib/v6/index.node" is installed via remote
[1/1] scripts.install skia-canvas@latest finished in 2s
✔ Run 1 scripts

```

**Comment by ltxhhz** [comment]
非常感谢
