### ISSUE TITLE
cdn站点错误，是停服还是bug？

### ISSUE THREAD

**Issue by palxiao** [cnpm/cnpmcore#725]
一些依赖无法安装

![image](https://github.com/user-attachments/assets/451fb185-4e6b-4843-bfaf-04c1d7f905dd)

发现是 https://cdn.npmmirror.com/ 无法正常访问，不知是bug还是已经停服？

![image](https://github.com/user-attachments/assets/ecb9a8bf-4271-4dc2-be06-97718841f565)

**Comment by hezhengxu2018** [comment]
本来就是无法直接访问的，需要访问文件的地址才能下载，本身是一个对象存储

**Comment by elrrrrrrr** [comment]
https://cdn.npmmirror.com/packages/typescript/5.6.3/typescript-5.6.3.tgz

🔼 应该可以访问到的

cdn.npmmirror.com 这个域名在请求的时候是不直接对外的，正常会通过 `https://registry.npmmirror.com/typescript/-/typescript-5.6.3.tgz` 跳转

**Comment by palxiao** [comment]
应该是网络问题
