### ISSUE TITLE
请问是否可以增加2个chrome-for-testing中的json文件的同步

### ISSUE THREAD

**Issue by JokerYF** [cnpm/cnpmcore#730]
RT
请求同步的json文件：
https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json
https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json
请求同步原因：
这两个json文件原本是我在自己的gitee项目中，同步github项目实现的，然后直接请求获取版本信息，今天突然发现gitee禁止我这个项目中直接请求json文件了
https://gitee.com/Joker_JH/DriverRelease/raw/master/ChromeDriverLastVersion.json
![image](https://github.com/user-attachments/assets/29b775f5-4c48-48e6-b650-7f9565ca65cb)
是否可以帮忙同步一下这两个json文件，文件大小并不大，不会占用太多资源
![image](https://github.com/user-attachments/assets/42661503-1e7f-4d74-8304-14c50bd0669b)
![image](https://github.com/user-attachments/assets/d39c8bf8-76a8-4ee9-8e48-ef317f216026)

**Comment by fengmk2** [comment]
这2个是动态更新的数据，无法同步。

**Comment by JokerYF** [comment]
> 这2个是动态更新的数据，无法同步。

能不能把这两个文件的内容同步保存到chrome-for-testing目录下，并以json文件形式保存？只需要定时更新就可以了，文件中有时间戳记录文件最后更新时间，可以判断是否需要更新文件内容，如果时间戳变化，将新文件同步一下即可

**Comment by fengmk2** [comment]
可以来提交 pr 贡献代码

**Comment by JokerYF** [comment]
抱歉抱歉，我TS水平不太行。。。

**Comment by JokerYF** [comment]
支持Python提交不？。。。

**Comment by fengmk2** [comment]
我尝试一下

**Comment by fengmk2** [comment]
https://registry.npmmirror.com/-/binary/chrome-for-testing/known-good-versions-with-downloads.json
https://registry.npmmirror.com/-/binary/chrome-for-testing/last-known-good-versions.json
https://registry.npmmirror.com/-/binary/chrome-for-testing/latest-patch-versions-per-build.json

**Comment by JokerYF** [comment]
非常感谢更新！

**Comment by fengmk2** [comment]
> 非常感谢更新！

希望能够帮助到你
