### ISSUE TITLE
【求助】线上服务占用磁盘空间不断增大，应该怎么优化？

### ISSUE THREAD

**Issue by shilucus** [cnpm/cnpmcore#744]
近期我司运维发现部署cnpmcore服务的机器，磁盘空间快被占满了。发现dist目录生成了很多core.xxx文件，请问这些文件是做什么用的， 可以清理吗？ 

线上版本：v3.13.2

![image](https://github.com/user-attachments/assets/945cd55f-7888-43f5-9aee-92d4f882835a)

**Comment by elrrrrrrr** [comment]
这是 linux 生成的 coredump 文件，是进程崩溃后系统生成的，可以用分析异常退出原因。

关闭 coredump 在不同操作系统的处理流程不太一样，以下是 AI 返回的一些信息参考，可以尝试下 🙏🏻

在 Linux 系统中，可以通过几种方法来关闭 core dump 文件的生成。以下是几种常用的方法：

### 方法 1: 使用 `ulimit` 命令
`ulimit` 命令可以用来设置用户进程的资源限制。要关闭 core dump 文件生成，可以将 core 文件大小限制设置为 0。

1. 临时关闭 core dump 文件生成（只对当前会话有效）：
   ```bash
   ulimit -c 0
   ```

2. 永久关闭 core dump 文件生成（对所有会话有效）：
   编辑 `/etc/security/limits.conf` 文件，添加以下两行：
   ```plaintext
   * hard core 0
   * soft core 0
   ```

### 方法 2: 修改 `/proc` 文件系统
通过修改 `/proc/sys/kernel/core_pattern` 文件，可以控制 core dump 文件的生成。

1. 检查当前的 core pattern 设置：
   ```bash
   cat /proc/sys/kernel/core_pattern
   ```

2. 将 core pattern 设置为空以禁用 core dump：
   ```bash
   echo "|/bin/false" > /proc/sys/kernel/core_pattern
   ```

3. 为了使这个设置永久生效，可以将其添加到 `/etc/sysctl.conf` 文件中：
   ```plaintext
   kernel.core_pattern = |/bin/false
   ```
   然后运行以下命令以应用配置：
   ```bash
   sysctl -p
   ```

### 方法 3: 使用 systemd-coredump（适用于 systemd 系统）
如果系统使用 systemd 管理服务，可以通过配置 `systemd-coredump` 来禁用 core dump。

1. 创建或编辑 `/etc/systemd/coredump.conf` 文件，添加以下内容：
   ```plaintext
   [Coredump]
   Storage=none
   ```
   
2. 重新加载 systemd 配置：
   ```bash
   systemctl daemon-reload
   ```

这几种方法都可以有效地关闭 Linux 系统中的 core dump 文件生成。根据需要选择适合的方法进行配置。

**Comment by shilucus** [comment]
> 这是 linux 生成的 coredump 文件，是进程崩溃后系统生成的，可以用分析异常退出原因。
> 
> 关闭 coredump 在不同操作系统的处理流程不太一样，以下是 AI 返回的一些信息参考，可以尝试下 🙏🏻
> 
> 在 Linux 系统中，可以通过几种方法来关闭 core dump 文件的生成。以下是几种常用的方法：
> 
> ### 方法 1: 使用 `ulimit` 命令
> `ulimit` 命令可以用来设置用户进程的资源限制。要关闭 core dump 文件生成，可以将 core 文件大小限制设置为 0。
> 
> 1. 临时关闭 core dump 文件生成（只对当前会话有效）：
>    ```shell
>    ulimit -c 0
>    ```
> 2. 永久关闭 core dump 文件生成（对所有会话有效）：
>    编辑 `/etc/security/limits.conf` 文件，添加以下两行：
>    ```
>    * hard core 0
>    * soft core 0
>    ```
> 
> ### 方法 2: 修改 `/proc` 文件系统
> 通过修改 `/proc/sys/kernel/core_pattern` 文件，可以控制 core dump 文件的生成。
> 
> 1. 检查当前的 core pattern 设置：
>    ```shell
>    cat /proc/sys/kernel/core_pattern
>    ```
> 2. 将 core pattern 设置为空以禁用 core dump：
>    ```shell
>    echo "|/bin/false" > /proc/sys/kernel/core_pattern
>    ```
> 3. 为了使这个设置永久生效，可以将其添加到 `/etc/sysctl.conf` 文件中：
>    ```
>    kernel.core_pattern = |/bin/false
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    然后运行以下命令以应用配置：
>    ```shell
>    sysctl -p
>    ```
> 
> ### 方法 3: 使用 systemd-coredump（适用于 systemd 系统）
> 如果系统使用 systemd 管理服务，可以通过配置 `systemd-coredump` 来禁用 core dump。
> 
> 1. 创建或编辑 `/etc/systemd/coredump.conf` 文件，添加以下内容：
>    ```
>    [Coredump]
>    Storage=none
>    ```
> 2. 重新加载 systemd 配置：
>    ```shell
>    systemctl daemon-reload
>    ```
> 
> 这几种方法都可以有效地关闭 Linux 系统中的 core dump 文件生成。根据需要选择适合的方法进行配置。

感谢回复
